// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/dictionary.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "syntaxnet/dictionary.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace syntaxnet {
class StringToStringPairDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StringToStringPair> {
} _StringToStringPair_default_instance_;
class StringToStringMapDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StringToStringMap> {
} _StringToStringMap_default_instance_;
class AffixTableEntry_AffixEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<AffixTableEntry_AffixEntry> {
} _AffixTableEntry_AffixEntry_default_instance_;
class AffixTableEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<AffixTableEntry> {
} _AffixTableEntry_default_instance_;
class TokenEmbedding_VectorDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TokenEmbedding_Vector> {
} _TokenEmbedding_Vector_default_instance_;
class TokenEmbeddingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TokenEmbedding> {
} _TokenEmbedding_default_instance_;

namespace protobuf_syntaxnet_2fdictionary_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[6];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringPair, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringPair, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringPair, value_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringMap, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringToStringMap, pair_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry_AffixEntry, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry_AffixEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry_AffixEntry, form_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry_AffixEntry, length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry_AffixEntry, shorter_id_),
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry, max_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AffixTableEntry, affix_),
  0,
  1,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding_Vector, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding_Vector, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding_Vector, values_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding, token_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding, count_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenEmbedding, vector_),
  0,
  2,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(StringToStringPair)},
  { 8, 13, sizeof(StringToStringMap)},
  { 14, 21, sizeof(AffixTableEntry_AffixEntry)},
  { 24, 31, sizeof(AffixTableEntry)},
  { 34, 39, sizeof(TokenEmbedding_Vector)},
  { 40, 47, sizeof(TokenEmbedding)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_StringToStringPair_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_StringToStringMap_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AffixTableEntry_AffixEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AffixTableEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TokenEmbedding_Vector_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TokenEmbedding_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "syntaxnet/dictionary.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

}  // namespace

void TableStruct::Shutdown() {
  _StringToStringPair_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _StringToStringMap_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _AffixTableEntry_AffixEntry_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _AffixTableEntry_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _TokenEmbedding_Vector_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
  _TokenEmbedding_default_instance_.Shutdown();
  delete file_level_metadata[5].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _StringToStringPair_default_instance_.DefaultConstruct();
  _StringToStringMap_default_instance_.DefaultConstruct();
  _AffixTableEntry_AffixEntry_default_instance_.DefaultConstruct();
  _AffixTableEntry_default_instance_.DefaultConstruct();
  _TokenEmbedding_Vector_default_instance_.DefaultConstruct();
  _TokenEmbedding_default_instance_.DefaultConstruct();
  _TokenEmbedding_default_instance_.get_mutable()->vector_ = const_cast< ::syntaxnet::TokenEmbedding_Vector*>(
      ::syntaxnet::TokenEmbedding_Vector::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\032syntaxnet/dictionary.proto\022\tsyntaxnet\""
      "0\n\022StringToStringPair\022\013\n\003key\030\001 \002(\t\022\r\n\005va"
      "lue\030\002 \002(\t\"@\n\021StringToStringMap\022+\n\004pair\030\001"
      " \003(\0132\035.syntaxnet.StringToStringPair\"\251\001\n\017"
      "AffixTableEntry\022\014\n\004type\030\001 \002(\t\022\022\n\nmax_len"
      "gth\030\002 \002(\005\0224\n\005affix\030\003 \003(\0132%.syntaxnet.Aff"
      "ixTableEntry.AffixEntry\032>\n\nAffixEntry\022\014\n"
      "\004form\030\001 \002(\t\022\016\n\006length\030\002 \002(\005\022\022\n\nshorter_i"
      "d\030\003 \002(\005\"~\n\016TokenEmbedding\022\r\n\005token\030\001 \002(\014"
      "\022\r\n\005count\030\003 \001(\003\0220\n\006vector\030\002 \001(\0132 .syntax"
      "net.TokenEmbedding.Vector\032\034\n\006Vector\022\022\n\006v"
      "alues\030\001 \003(\002B\002\020\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 455);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "syntaxnet/dictionary.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_syntaxnet_2fdictionary_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StringToStringPair::kKeyFieldNumber;
const int StringToStringPair::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StringToStringPair::StringToStringPair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.StringToStringPair)
}
StringToStringPair::StringToStringPair(const StringToStringPair& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_key()) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_value()) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:syntaxnet.StringToStringPair)
}

void StringToStringPair::SharedCtor() {
  _cached_size_ = 0;
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

StringToStringPair::~StringToStringPair() {
  // @@protoc_insertion_point(destructor:syntaxnet.StringToStringPair)
  SharedDtor();
}

void StringToStringPair::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StringToStringPair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StringToStringPair::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[0].descriptor;
}

const StringToStringPair& StringToStringPair::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

StringToStringPair* StringToStringPair::New(::google::protobuf::Arena* arena) const {
  StringToStringPair* n = new StringToStringPair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StringToStringPair::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.StringToStringPair)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_key()) {
      GOOGLE_DCHECK(!key_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*key_.UnsafeRawStringPointer())->clear();
    }
    if (has_value()) {
      GOOGLE_DCHECK(!value_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*value_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool StringToStringPair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.StringToStringPair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.StringToStringPair.key");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.StringToStringPair.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.StringToStringPair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.StringToStringPair)
  return false;
#undef DO_
}

void StringToStringPair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.StringToStringPair)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.StringToStringPair.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.StringToStringPair.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.StringToStringPair)
}

::google::protobuf::uint8* StringToStringPair::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.StringToStringPair)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.StringToStringPair.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.StringToStringPair.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.StringToStringPair)
  return target;
}

size_t StringToStringPair::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:syntaxnet.StringToStringPair)
  size_t total_size = 0;

  if (has_key()) {
    // required string key = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  if (has_value()) {
    // required string value = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  return total_size;
}
size_t StringToStringPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.StringToStringPair)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string key = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());

    // required string value = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringToStringPair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.StringToStringPair)
  GOOGLE_DCHECK_NE(&from, this);
  const StringToStringPair* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StringToStringPair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.StringToStringPair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.StringToStringPair)
    MergeFrom(*source);
  }
}

void StringToStringPair::MergeFrom(const StringToStringPair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.StringToStringPair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_key()) {
      set_has_key();
      key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
    }
    if (from.has_value()) {
      set_has_value();
      value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
    }
  }
}

void StringToStringPair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.StringToStringPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StringToStringPair::CopyFrom(const StringToStringPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.StringToStringPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringToStringPair::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void StringToStringPair::Swap(StringToStringPair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StringToStringPair::InternalSwap(StringToStringPair* other) {
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StringToStringPair::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StringToStringPair

// required string key = 1;
bool StringToStringPair::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void StringToStringPair::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
void StringToStringPair::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
void StringToStringPair::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
const ::std::string& StringToStringPair::key() const {
  // @@protoc_insertion_point(field_get:syntaxnet.StringToStringPair.key)
  return key_.GetNoArena();
}
void StringToStringPair::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.StringToStringPair.key)
}
#if LANG_CXX11
void StringToStringPair::set_key(::std::string&& value) {
  set_has_key();
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.StringToStringPair.key)
}
#endif
void StringToStringPair::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.StringToStringPair.key)
}
void StringToStringPair::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.StringToStringPair.key)
}
::std::string* StringToStringPair::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:syntaxnet.StringToStringPair.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StringToStringPair::release_key() {
  // @@protoc_insertion_point(field_release:syntaxnet.StringToStringPair.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StringToStringPair::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.StringToStringPair.key)
}

// required string value = 2;
bool StringToStringPair::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void StringToStringPair::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
void StringToStringPair::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
void StringToStringPair::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
const ::std::string& StringToStringPair::value() const {
  // @@protoc_insertion_point(field_get:syntaxnet.StringToStringPair.value)
  return value_.GetNoArena();
}
void StringToStringPair::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.StringToStringPair.value)
}
#if LANG_CXX11
void StringToStringPair::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.StringToStringPair.value)
}
#endif
void StringToStringPair::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.StringToStringPair.value)
}
void StringToStringPair::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.StringToStringPair.value)
}
::std::string* StringToStringPair::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:syntaxnet.StringToStringPair.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StringToStringPair::release_value() {
  // @@protoc_insertion_point(field_release:syntaxnet.StringToStringPair.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StringToStringPair::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.StringToStringPair.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StringToStringMap::kPairFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StringToStringMap::StringToStringMap()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.StringToStringMap)
}
StringToStringMap::StringToStringMap(const StringToStringMap& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      pair_(from.pair_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.StringToStringMap)
}

void StringToStringMap::SharedCtor() {
  _cached_size_ = 0;
}

StringToStringMap::~StringToStringMap() {
  // @@protoc_insertion_point(destructor:syntaxnet.StringToStringMap)
  SharedDtor();
}

void StringToStringMap::SharedDtor() {
}

void StringToStringMap::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StringToStringMap::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[1].descriptor;
}

const StringToStringMap& StringToStringMap::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

StringToStringMap* StringToStringMap::New(::google::protobuf::Arena* arena) const {
  StringToStringMap* n = new StringToStringMap;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StringToStringMap::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.StringToStringMap)
  pair_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool StringToStringMap::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.StringToStringMap)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .syntaxnet.StringToStringPair pair = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_pair()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.StringToStringMap)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.StringToStringMap)
  return false;
#undef DO_
}

void StringToStringMap::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.StringToStringMap)
  // repeated .syntaxnet.StringToStringPair pair = 1;
  for (unsigned int i = 0, n = this->pair_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->pair(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.StringToStringMap)
}

::google::protobuf::uint8* StringToStringMap::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.StringToStringMap)
  // repeated .syntaxnet.StringToStringPair pair = 1;
  for (unsigned int i = 0, n = this->pair_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->pair(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.StringToStringMap)
  return target;
}

size_t StringToStringMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.StringToStringMap)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.StringToStringPair pair = 1;
  {
    unsigned int count = this->pair_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->pair(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringToStringMap::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.StringToStringMap)
  GOOGLE_DCHECK_NE(&from, this);
  const StringToStringMap* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StringToStringMap>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.StringToStringMap)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.StringToStringMap)
    MergeFrom(*source);
  }
}

void StringToStringMap::MergeFrom(const StringToStringMap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.StringToStringMap)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pair_.MergeFrom(from.pair_);
}

void StringToStringMap::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.StringToStringMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StringToStringMap::CopyFrom(const StringToStringMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.StringToStringMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringToStringMap::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->pair())) return false;
  return true;
}

void StringToStringMap::Swap(StringToStringMap* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StringToStringMap::InternalSwap(StringToStringMap* other) {
  pair_.UnsafeArenaSwap(&other->pair_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StringToStringMap::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StringToStringMap

// repeated .syntaxnet.StringToStringPair pair = 1;
int StringToStringMap::pair_size() const {
  return pair_.size();
}
void StringToStringMap::clear_pair() {
  pair_.Clear();
}
const ::syntaxnet::StringToStringPair& StringToStringMap::pair(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.StringToStringMap.pair)
  return pair_.Get(index);
}
::syntaxnet::StringToStringPair* StringToStringMap::mutable_pair(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.StringToStringMap.pair)
  return pair_.Mutable(index);
}
::syntaxnet::StringToStringPair* StringToStringMap::add_pair() {
  // @@protoc_insertion_point(field_add:syntaxnet.StringToStringMap.pair)
  return pair_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::StringToStringPair >*
StringToStringMap::mutable_pair() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.StringToStringMap.pair)
  return &pair_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::StringToStringPair >&
StringToStringMap::pair() const {
  // @@protoc_insertion_point(field_list:syntaxnet.StringToStringMap.pair)
  return pair_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AffixTableEntry_AffixEntry::kFormFieldNumber;
const int AffixTableEntry_AffixEntry::kLengthFieldNumber;
const int AffixTableEntry_AffixEntry::kShorterIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AffixTableEntry_AffixEntry::AffixTableEntry_AffixEntry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.AffixTableEntry.AffixEntry)
}
AffixTableEntry_AffixEntry::AffixTableEntry_AffixEntry(const AffixTableEntry_AffixEntry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  form_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_form()) {
    form_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.form_);
  }
  ::memcpy(&length_, &from.length_,
    reinterpret_cast<char*>(&shorter_id_) -
    reinterpret_cast<char*>(&length_) + sizeof(shorter_id_));
  // @@protoc_insertion_point(copy_constructor:syntaxnet.AffixTableEntry.AffixEntry)
}

void AffixTableEntry_AffixEntry::SharedCtor() {
  _cached_size_ = 0;
  form_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&length_, 0, reinterpret_cast<char*>(&shorter_id_) -
    reinterpret_cast<char*>(&length_) + sizeof(shorter_id_));
}

AffixTableEntry_AffixEntry::~AffixTableEntry_AffixEntry() {
  // @@protoc_insertion_point(destructor:syntaxnet.AffixTableEntry.AffixEntry)
  SharedDtor();
}

void AffixTableEntry_AffixEntry::SharedDtor() {
  form_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AffixTableEntry_AffixEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AffixTableEntry_AffixEntry::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[2].descriptor;
}

const AffixTableEntry_AffixEntry& AffixTableEntry_AffixEntry::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

AffixTableEntry_AffixEntry* AffixTableEntry_AffixEntry::New(::google::protobuf::Arena* arena) const {
  AffixTableEntry_AffixEntry* n = new AffixTableEntry_AffixEntry;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AffixTableEntry_AffixEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.AffixTableEntry.AffixEntry)
  if (has_form()) {
    GOOGLE_DCHECK(!form_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*form_.UnsafeRawStringPointer())->clear();
  }
  if (_has_bits_[0 / 32] & 6u) {
    ::memset(&length_, 0, reinterpret_cast<char*>(&shorter_id_) -
      reinterpret_cast<char*>(&length_) + sizeof(shorter_id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AffixTableEntry_AffixEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.AffixTableEntry.AffixEntry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string form = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_form()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->form().data(), this->form().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.AffixTableEntry.AffixEntry.form");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 shorter_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_shorter_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &shorter_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.AffixTableEntry.AffixEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.AffixTableEntry.AffixEntry)
  return false;
#undef DO_
}

void AffixTableEntry_AffixEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.AffixTableEntry.AffixEntry)
  // required string form = 1;
  if (has_form()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->form().data(), this->form().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AffixTableEntry.AffixEntry.form");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->form(), output);
  }

  // required int32 length = 2;
  if (has_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->length(), output);
  }

  // required int32 shorter_id = 3;
  if (has_shorter_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->shorter_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.AffixTableEntry.AffixEntry)
}

::google::protobuf::uint8* AffixTableEntry_AffixEntry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.AffixTableEntry.AffixEntry)
  // required string form = 1;
  if (has_form()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->form().data(), this->form().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AffixTableEntry.AffixEntry.form");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->form(), target);
  }

  // required int32 length = 2;
  if (has_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->length(), target);
  }

  // required int32 shorter_id = 3;
  if (has_shorter_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->shorter_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.AffixTableEntry.AffixEntry)
  return target;
}

size_t AffixTableEntry_AffixEntry::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:syntaxnet.AffixTableEntry.AffixEntry)
  size_t total_size = 0;

  if (has_form()) {
    // required string form = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->form());
  }

  if (has_length()) {
    // required int32 length = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());
  }

  if (has_shorter_id()) {
    // required int32 shorter_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->shorter_id());
  }

  return total_size;
}
size_t AffixTableEntry_AffixEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.AffixTableEntry.AffixEntry)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string form = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->form());

    // required int32 length = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());

    // required int32 shorter_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->shorter_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AffixTableEntry_AffixEntry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.AffixTableEntry.AffixEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const AffixTableEntry_AffixEntry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AffixTableEntry_AffixEntry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.AffixTableEntry.AffixEntry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.AffixTableEntry.AffixEntry)
    MergeFrom(*source);
  }
}

void AffixTableEntry_AffixEntry::MergeFrom(const AffixTableEntry_AffixEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.AffixTableEntry.AffixEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 7u) {
    if (from.has_form()) {
      set_has_form();
      form_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.form_);
    }
    if (from.has_length()) {
      set_length(from.length());
    }
    if (from.has_shorter_id()) {
      set_shorter_id(from.shorter_id());
    }
  }
}

void AffixTableEntry_AffixEntry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.AffixTableEntry.AffixEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AffixTableEntry_AffixEntry::CopyFrom(const AffixTableEntry_AffixEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.AffixTableEntry.AffixEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AffixTableEntry_AffixEntry::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void AffixTableEntry_AffixEntry::Swap(AffixTableEntry_AffixEntry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AffixTableEntry_AffixEntry::InternalSwap(AffixTableEntry_AffixEntry* other) {
  form_.Swap(&other->form_);
  std::swap(length_, other->length_);
  std::swap(shorter_id_, other->shorter_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AffixTableEntry_AffixEntry::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AffixTableEntry_AffixEntry

// required string form = 1;
bool AffixTableEntry_AffixEntry::has_form() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AffixTableEntry_AffixEntry::set_has_form() {
  _has_bits_[0] |= 0x00000001u;
}
void AffixTableEntry_AffixEntry::clear_has_form() {
  _has_bits_[0] &= ~0x00000001u;
}
void AffixTableEntry_AffixEntry::clear_form() {
  form_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_form();
}
const ::std::string& AffixTableEntry_AffixEntry::form() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.AffixEntry.form)
  return form_.GetNoArena();
}
void AffixTableEntry_AffixEntry::set_form(const ::std::string& value) {
  set_has_form();
  form_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.AffixTableEntry.AffixEntry.form)
}
#if LANG_CXX11
void AffixTableEntry_AffixEntry::set_form(::std::string&& value) {
  set_has_form();
  form_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.AffixTableEntry.AffixEntry.form)
}
#endif
void AffixTableEntry_AffixEntry::set_form(const char* value) {
  set_has_form();
  form_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.AffixTableEntry.AffixEntry.form)
}
void AffixTableEntry_AffixEntry::set_form(const char* value, size_t size) {
  set_has_form();
  form_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.AffixTableEntry.AffixEntry.form)
}
::std::string* AffixTableEntry_AffixEntry::mutable_form() {
  set_has_form();
  // @@protoc_insertion_point(field_mutable:syntaxnet.AffixTableEntry.AffixEntry.form)
  return form_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AffixTableEntry_AffixEntry::release_form() {
  // @@protoc_insertion_point(field_release:syntaxnet.AffixTableEntry.AffixEntry.form)
  clear_has_form();
  return form_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AffixTableEntry_AffixEntry::set_allocated_form(::std::string* form) {
  if (form != NULL) {
    set_has_form();
  } else {
    clear_has_form();
  }
  form_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), form);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.AffixTableEntry.AffixEntry.form)
}

// required int32 length = 2;
bool AffixTableEntry_AffixEntry::has_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void AffixTableEntry_AffixEntry::set_has_length() {
  _has_bits_[0] |= 0x00000002u;
}
void AffixTableEntry_AffixEntry::clear_has_length() {
  _has_bits_[0] &= ~0x00000002u;
}
void AffixTableEntry_AffixEntry::clear_length() {
  length_ = 0;
  clear_has_length();
}
::google::protobuf::int32 AffixTableEntry_AffixEntry::length() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.AffixEntry.length)
  return length_;
}
void AffixTableEntry_AffixEntry::set_length(::google::protobuf::int32 value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.AffixTableEntry.AffixEntry.length)
}

// required int32 shorter_id = 3;
bool AffixTableEntry_AffixEntry::has_shorter_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void AffixTableEntry_AffixEntry::set_has_shorter_id() {
  _has_bits_[0] |= 0x00000004u;
}
void AffixTableEntry_AffixEntry::clear_has_shorter_id() {
  _has_bits_[0] &= ~0x00000004u;
}
void AffixTableEntry_AffixEntry::clear_shorter_id() {
  shorter_id_ = 0;
  clear_has_shorter_id();
}
::google::protobuf::int32 AffixTableEntry_AffixEntry::shorter_id() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.AffixEntry.shorter_id)
  return shorter_id_;
}
void AffixTableEntry_AffixEntry::set_shorter_id(::google::protobuf::int32 value) {
  set_has_shorter_id();
  shorter_id_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.AffixTableEntry.AffixEntry.shorter_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AffixTableEntry::kTypeFieldNumber;
const int AffixTableEntry::kMaxLengthFieldNumber;
const int AffixTableEntry::kAffixFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AffixTableEntry::AffixTableEntry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.AffixTableEntry)
}
AffixTableEntry::AffixTableEntry(const AffixTableEntry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      affix_(from.affix_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type()) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  max_length_ = from.max_length_;
  // @@protoc_insertion_point(copy_constructor:syntaxnet.AffixTableEntry)
}

void AffixTableEntry::SharedCtor() {
  _cached_size_ = 0;
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  max_length_ = 0;
}

AffixTableEntry::~AffixTableEntry() {
  // @@protoc_insertion_point(destructor:syntaxnet.AffixTableEntry)
  SharedDtor();
}

void AffixTableEntry::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AffixTableEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AffixTableEntry::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[3].descriptor;
}

const AffixTableEntry& AffixTableEntry::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

AffixTableEntry* AffixTableEntry::New(::google::protobuf::Arena* arena) const {
  AffixTableEntry* n = new AffixTableEntry;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AffixTableEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.AffixTableEntry)
  affix_.Clear();
  if (has_type()) {
    GOOGLE_DCHECK(!type_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*type_.UnsafeRawStringPointer())->clear();
  }
  max_length_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AffixTableEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.AffixTableEntry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.AffixTableEntry.type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 max_length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_max_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .syntaxnet.AffixTableEntry.AffixEntry affix = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_affix()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.AffixTableEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.AffixTableEntry)
  return false;
#undef DO_
}

void AffixTableEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.AffixTableEntry)
  // required string type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AffixTableEntry.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // required int32 max_length = 2;
  if (has_max_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->max_length(), output);
  }

  // repeated .syntaxnet.AffixTableEntry.AffixEntry affix = 3;
  for (unsigned int i = 0, n = this->affix_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->affix(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.AffixTableEntry)
}

::google::protobuf::uint8* AffixTableEntry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.AffixTableEntry)
  // required string type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AffixTableEntry.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // required int32 max_length = 2;
  if (has_max_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->max_length(), target);
  }

  // repeated .syntaxnet.AffixTableEntry.AffixEntry affix = 3;
  for (unsigned int i = 0, n = this->affix_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->affix(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.AffixTableEntry)
  return target;
}

size_t AffixTableEntry::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:syntaxnet.AffixTableEntry)
  size_t total_size = 0;

  if (has_type()) {
    // required string type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  if (has_max_length()) {
    // required int32 max_length = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->max_length());
  }

  return total_size;
}
size_t AffixTableEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.AffixTableEntry)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());

    // required int32 max_length = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->max_length());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .syntaxnet.AffixTableEntry.AffixEntry affix = 3;
  {
    unsigned int count = this->affix_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->affix(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AffixTableEntry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.AffixTableEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const AffixTableEntry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AffixTableEntry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.AffixTableEntry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.AffixTableEntry)
    MergeFrom(*source);
  }
}

void AffixTableEntry::MergeFrom(const AffixTableEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.AffixTableEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  affix_.MergeFrom(from.affix_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_type()) {
      set_has_type();
      type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
    }
    if (from.has_max_length()) {
      set_max_length(from.max_length());
    }
  }
}

void AffixTableEntry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.AffixTableEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AffixTableEntry::CopyFrom(const AffixTableEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.AffixTableEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AffixTableEntry::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->affix())) return false;
  return true;
}

void AffixTableEntry::Swap(AffixTableEntry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AffixTableEntry::InternalSwap(AffixTableEntry* other) {
  affix_.UnsafeArenaSwap(&other->affix_);
  type_.Swap(&other->type_);
  std::swap(max_length_, other->max_length_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AffixTableEntry::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AffixTableEntry

// required string type = 1;
bool AffixTableEntry::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AffixTableEntry::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
void AffixTableEntry::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void AffixTableEntry::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
const ::std::string& AffixTableEntry::type() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.type)
  return type_.GetNoArena();
}
void AffixTableEntry::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.AffixTableEntry.type)
}
#if LANG_CXX11
void AffixTableEntry::set_type(::std::string&& value) {
  set_has_type();
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.AffixTableEntry.type)
}
#endif
void AffixTableEntry::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.AffixTableEntry.type)
}
void AffixTableEntry::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.AffixTableEntry.type)
}
::std::string* AffixTableEntry::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:syntaxnet.AffixTableEntry.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AffixTableEntry::release_type() {
  // @@protoc_insertion_point(field_release:syntaxnet.AffixTableEntry.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AffixTableEntry::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.AffixTableEntry.type)
}

// required int32 max_length = 2;
bool AffixTableEntry::has_max_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void AffixTableEntry::set_has_max_length() {
  _has_bits_[0] |= 0x00000002u;
}
void AffixTableEntry::clear_has_max_length() {
  _has_bits_[0] &= ~0x00000002u;
}
void AffixTableEntry::clear_max_length() {
  max_length_ = 0;
  clear_has_max_length();
}
::google::protobuf::int32 AffixTableEntry::max_length() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.max_length)
  return max_length_;
}
void AffixTableEntry::set_max_length(::google::protobuf::int32 value) {
  set_has_max_length();
  max_length_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.AffixTableEntry.max_length)
}

// repeated .syntaxnet.AffixTableEntry.AffixEntry affix = 3;
int AffixTableEntry::affix_size() const {
  return affix_.size();
}
void AffixTableEntry::clear_affix() {
  affix_.Clear();
}
const ::syntaxnet::AffixTableEntry_AffixEntry& AffixTableEntry::affix(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.AffixTableEntry.affix)
  return affix_.Get(index);
}
::syntaxnet::AffixTableEntry_AffixEntry* AffixTableEntry::mutable_affix(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.AffixTableEntry.affix)
  return affix_.Mutable(index);
}
::syntaxnet::AffixTableEntry_AffixEntry* AffixTableEntry::add_affix() {
  // @@protoc_insertion_point(field_add:syntaxnet.AffixTableEntry.affix)
  return affix_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::AffixTableEntry_AffixEntry >*
AffixTableEntry::mutable_affix() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.AffixTableEntry.affix)
  return &affix_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::AffixTableEntry_AffixEntry >&
AffixTableEntry::affix() const {
  // @@protoc_insertion_point(field_list:syntaxnet.AffixTableEntry.affix)
  return affix_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenEmbedding_Vector::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TokenEmbedding_Vector::TokenEmbedding_Vector()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.TokenEmbedding.Vector)
}
TokenEmbedding_Vector::TokenEmbedding_Vector(const TokenEmbedding_Vector& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      values_(from.values_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.TokenEmbedding.Vector)
}

void TokenEmbedding_Vector::SharedCtor() {
  _cached_size_ = 0;
}

TokenEmbedding_Vector::~TokenEmbedding_Vector() {
  // @@protoc_insertion_point(destructor:syntaxnet.TokenEmbedding.Vector)
  SharedDtor();
}

void TokenEmbedding_Vector::SharedDtor() {
}

void TokenEmbedding_Vector::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TokenEmbedding_Vector::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[4].descriptor;
}

const TokenEmbedding_Vector& TokenEmbedding_Vector::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

TokenEmbedding_Vector* TokenEmbedding_Vector::New(::google::protobuf::Arena* arena) const {
  TokenEmbedding_Vector* n = new TokenEmbedding_Vector;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TokenEmbedding_Vector::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.TokenEmbedding.Vector)
  values_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TokenEmbedding_Vector::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.TokenEmbedding.Vector)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float values = 1 [packed = true];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_values())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(13u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_values())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.TokenEmbedding.Vector)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.TokenEmbedding.Vector)
  return false;
#undef DO_
}

void TokenEmbedding_Vector::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.TokenEmbedding.Vector)
  // repeated float values = 1 [packed = true];
  if (this->values_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_values_cached_byte_size_);
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->values().data(), this->values_size(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.TokenEmbedding.Vector)
}

::google::protobuf::uint8* TokenEmbedding_Vector::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.TokenEmbedding.Vector)
  // repeated float values = 1 [packed = true];
  if (this->values_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _values_cached_byte_size_, target);
  }
  for (int i = 0, n = this->values_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->values(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.TokenEmbedding.Vector)
  return target;
}

size_t TokenEmbedding_Vector::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.TokenEmbedding.Vector)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated float values = 1 [packed = true];
  {
    unsigned int count = this->values_size();
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _values_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TokenEmbedding_Vector::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.TokenEmbedding.Vector)
  GOOGLE_DCHECK_NE(&from, this);
  const TokenEmbedding_Vector* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TokenEmbedding_Vector>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.TokenEmbedding.Vector)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.TokenEmbedding.Vector)
    MergeFrom(*source);
  }
}

void TokenEmbedding_Vector::MergeFrom(const TokenEmbedding_Vector& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.TokenEmbedding.Vector)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  values_.MergeFrom(from.values_);
}

void TokenEmbedding_Vector::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.TokenEmbedding.Vector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TokenEmbedding_Vector::CopyFrom(const TokenEmbedding_Vector& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.TokenEmbedding.Vector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenEmbedding_Vector::IsInitialized() const {
  return true;
}

void TokenEmbedding_Vector::Swap(TokenEmbedding_Vector* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TokenEmbedding_Vector::InternalSwap(TokenEmbedding_Vector* other) {
  values_.UnsafeArenaSwap(&other->values_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TokenEmbedding_Vector::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[4];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenEmbedding_Vector

// repeated float values = 1 [packed = true];
int TokenEmbedding_Vector::values_size() const {
  return values_.size();
}
void TokenEmbedding_Vector::clear_values() {
  values_.Clear();
}
float TokenEmbedding_Vector::values(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenEmbedding.Vector.values)
  return values_.Get(index);
}
void TokenEmbedding_Vector::set_values(int index, float value) {
  values_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.TokenEmbedding.Vector.values)
}
void TokenEmbedding_Vector::add_values(float value) {
  values_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.TokenEmbedding.Vector.values)
}
const ::google::protobuf::RepeatedField< float >&
TokenEmbedding_Vector::values() const {
  // @@protoc_insertion_point(field_list:syntaxnet.TokenEmbedding.Vector.values)
  return values_;
}
::google::protobuf::RepeatedField< float >*
TokenEmbedding_Vector::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.TokenEmbedding.Vector.values)
  return &values_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenEmbedding::kTokenFieldNumber;
const int TokenEmbedding::kCountFieldNumber;
const int TokenEmbedding::kVectorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TokenEmbedding::TokenEmbedding()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.TokenEmbedding)
}
TokenEmbedding::TokenEmbedding(const TokenEmbedding& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_token()) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  if (from.has_vector()) {
    vector_ = new ::syntaxnet::TokenEmbedding_Vector(*from.vector_);
  } else {
    vector_ = NULL;
  }
  count_ = from.count_;
  // @@protoc_insertion_point(copy_constructor:syntaxnet.TokenEmbedding)
}

void TokenEmbedding::SharedCtor() {
  _cached_size_ = 0;
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&vector_, 0, reinterpret_cast<char*>(&count_) -
    reinterpret_cast<char*>(&vector_) + sizeof(count_));
}

TokenEmbedding::~TokenEmbedding() {
  // @@protoc_insertion_point(destructor:syntaxnet.TokenEmbedding)
  SharedDtor();
}

void TokenEmbedding::SharedDtor() {
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete vector_;
  }
}

void TokenEmbedding::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TokenEmbedding::descriptor() {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[5].descriptor;
}

const TokenEmbedding& TokenEmbedding::default_instance() {
  protobuf_syntaxnet_2fdictionary_2eproto::InitDefaults();
  return *internal_default_instance();
}

TokenEmbedding* TokenEmbedding::New(::google::protobuf::Arena* arena) const {
  TokenEmbedding* n = new TokenEmbedding;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TokenEmbedding::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.TokenEmbedding)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_token()) {
      GOOGLE_DCHECK(!token_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*token_.UnsafeRawStringPointer())->clear();
    }
    if (has_vector()) {
      GOOGLE_DCHECK(vector_ != NULL);
      vector_->::syntaxnet::TokenEmbedding_Vector::Clear();
    }
  }
  count_ = GOOGLE_LONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TokenEmbedding::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.TokenEmbedding)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes token = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_token()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .syntaxnet.TokenEmbedding.Vector vector = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_vector()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 count = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_count();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.TokenEmbedding)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.TokenEmbedding)
  return false;
#undef DO_
}

void TokenEmbedding::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.TokenEmbedding)
  // required bytes token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->token(), output);
  }

  // optional .syntaxnet.TokenEmbedding.Vector vector = 2;
  if (has_vector()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->vector_, output);
  }

  // optional int64 count = 3;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->count(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.TokenEmbedding)
}

::google::protobuf::uint8* TokenEmbedding::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.TokenEmbedding)
  // required bytes token = 1;
  if (has_token()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->token(), target);
  }

  // optional .syntaxnet.TokenEmbedding.Vector vector = 2;
  if (has_vector()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->vector_, false, target);
  }

  // optional int64 count = 3;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->count(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.TokenEmbedding)
  return target;
}

size_t TokenEmbedding::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.TokenEmbedding)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required bytes token = 1;
  if (has_token()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->token());
  }
  if (_has_bits_[0 / 32] & 6u) {
    // optional .syntaxnet.TokenEmbedding.Vector vector = 2;
    if (has_vector()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->vector_);
    }

    // optional int64 count = 3;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->count());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TokenEmbedding::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.TokenEmbedding)
  GOOGLE_DCHECK_NE(&from, this);
  const TokenEmbedding* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TokenEmbedding>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.TokenEmbedding)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.TokenEmbedding)
    MergeFrom(*source);
  }
}

void TokenEmbedding::MergeFrom(const TokenEmbedding& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.TokenEmbedding)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 7u) {
    if (from.has_token()) {
      set_has_token();
      token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
    }
    if (from.has_vector()) {
      mutable_vector()->::syntaxnet::TokenEmbedding_Vector::MergeFrom(from.vector());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
  }
}

void TokenEmbedding::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.TokenEmbedding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TokenEmbedding::CopyFrom(const TokenEmbedding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.TokenEmbedding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenEmbedding::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void TokenEmbedding::Swap(TokenEmbedding* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TokenEmbedding::InternalSwap(TokenEmbedding* other) {
  token_.Swap(&other->token_);
  std::swap(vector_, other->vector_);
  std::swap(count_, other->count_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TokenEmbedding::GetMetadata() const {
  protobuf_syntaxnet_2fdictionary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fdictionary_2eproto::file_level_metadata[5];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenEmbedding

// required bytes token = 1;
bool TokenEmbedding::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TokenEmbedding::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
void TokenEmbedding::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
void TokenEmbedding::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_token();
}
const ::std::string& TokenEmbedding::token() const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenEmbedding.token)
  return token_.GetNoArena();
}
void TokenEmbedding::set_token(const ::std::string& value) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.TokenEmbedding.token)
}
#if LANG_CXX11
void TokenEmbedding::set_token(::std::string&& value) {
  set_has_token();
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.TokenEmbedding.token)
}
#endif
void TokenEmbedding::set_token(const char* value) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.TokenEmbedding.token)
}
void TokenEmbedding::set_token(const void* value, size_t size) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.TokenEmbedding.token)
}
::std::string* TokenEmbedding::mutable_token() {
  set_has_token();
  // @@protoc_insertion_point(field_mutable:syntaxnet.TokenEmbedding.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TokenEmbedding::release_token() {
  // @@protoc_insertion_point(field_release:syntaxnet.TokenEmbedding.token)
  clear_has_token();
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TokenEmbedding::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    set_has_token();
  } else {
    clear_has_token();
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.TokenEmbedding.token)
}

// optional int64 count = 3;
bool TokenEmbedding::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void TokenEmbedding::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
void TokenEmbedding::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
void TokenEmbedding::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
  clear_has_count();
}
::google::protobuf::int64 TokenEmbedding::count() const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenEmbedding.count)
  return count_;
}
void TokenEmbedding::set_count(::google::protobuf::int64 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.TokenEmbedding.count)
}

// optional .syntaxnet.TokenEmbedding.Vector vector = 2;
bool TokenEmbedding::has_vector() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TokenEmbedding::set_has_vector() {
  _has_bits_[0] |= 0x00000002u;
}
void TokenEmbedding::clear_has_vector() {
  _has_bits_[0] &= ~0x00000002u;
}
void TokenEmbedding::clear_vector() {
  if (vector_ != NULL) vector_->::syntaxnet::TokenEmbedding_Vector::Clear();
  clear_has_vector();
}
const ::syntaxnet::TokenEmbedding_Vector& TokenEmbedding::vector() const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenEmbedding.vector)
  return vector_ != NULL ? *vector_
                         : *::syntaxnet::TokenEmbedding_Vector::internal_default_instance();
}
::syntaxnet::TokenEmbedding_Vector* TokenEmbedding::mutable_vector() {
  set_has_vector();
  if (vector_ == NULL) {
    vector_ = new ::syntaxnet::TokenEmbedding_Vector;
  }
  // @@protoc_insertion_point(field_mutable:syntaxnet.TokenEmbedding.vector)
  return vector_;
}
::syntaxnet::TokenEmbedding_Vector* TokenEmbedding::release_vector() {
  // @@protoc_insertion_point(field_release:syntaxnet.TokenEmbedding.vector)
  clear_has_vector();
  ::syntaxnet::TokenEmbedding_Vector* temp = vector_;
  vector_ = NULL;
  return temp;
}
void TokenEmbedding::set_allocated_vector(::syntaxnet::TokenEmbedding_Vector* vector) {
  delete vector_;
  vector_ = vector;
  if (vector) {
    set_has_vector();
  } else {
    clear_has_vector();
  }
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.TokenEmbedding.vector)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)
