// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/feature_extractor.proto

#ifndef PROTOBUF_syntaxnet_2ffeature_5fextractor_2eproto__INCLUDED
#define PROTOBUF_syntaxnet_2ffeature_5fextractor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace syntaxnet {
class FeatureExtractorDescriptor;
class FeatureExtractorDescriptorDefaultTypeInternal;
extern FeatureExtractorDescriptorDefaultTypeInternal _FeatureExtractorDescriptor_default_instance_;
class FeatureFunctionDescriptor;
class FeatureFunctionDescriptorDefaultTypeInternal;
extern FeatureFunctionDescriptorDefaultTypeInternal _FeatureFunctionDescriptor_default_instance_;
class Parameter;
class ParameterDefaultTypeInternal;
extern ParameterDefaultTypeInternal _Parameter_default_instance_;
}  // namespace syntaxnet

namespace syntaxnet {

namespace protobuf_syntaxnet_2ffeature_5fextractor_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_syntaxnet_2ffeature_5fextractor_2eproto

// ===================================================================

class Parameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:syntaxnet.Parameter) */ {
 public:
  Parameter();
  virtual ~Parameter();

  Parameter(const Parameter& from);

  inline Parameter& operator=(const Parameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Parameter& default_instance();

  static inline const Parameter* internal_default_instance() {
    return reinterpret_cast<const Parameter*>(
               &_Parameter_default_instance_);
  }

  void Swap(Parameter* other);

  // implements Message ----------------------------------------------

  inline Parameter* New() const PROTOBUF_FINAL { return New(NULL); }

  Parameter* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Parameter& from);
  void MergeFrom(const Parameter& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Parameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:syntaxnet.Parameter)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct  protobuf_syntaxnet_2ffeature_5fextractor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FeatureFunctionDescriptor : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:syntaxnet.FeatureFunctionDescriptor) */ {
 public:
  FeatureFunctionDescriptor();
  virtual ~FeatureFunctionDescriptor();

  FeatureFunctionDescriptor(const FeatureFunctionDescriptor& from);

  inline FeatureFunctionDescriptor& operator=(const FeatureFunctionDescriptor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FeatureFunctionDescriptor& default_instance();

  static inline const FeatureFunctionDescriptor* internal_default_instance() {
    return reinterpret_cast<const FeatureFunctionDescriptor*>(
               &_FeatureFunctionDescriptor_default_instance_);
  }

  void Swap(FeatureFunctionDescriptor* other);

  // implements Message ----------------------------------------------

  inline FeatureFunctionDescriptor* New() const PROTOBUF_FINAL { return New(NULL); }

  FeatureFunctionDescriptor* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FeatureFunctionDescriptor& from);
  void MergeFrom(const FeatureFunctionDescriptor& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FeatureFunctionDescriptor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .syntaxnet.Parameter parameter = 4;
  int parameter_size() const;
  void clear_parameter();
  static const int kParameterFieldNumber = 4;
  const ::syntaxnet::Parameter& parameter(int index) const;
  ::syntaxnet::Parameter* mutable_parameter(int index);
  ::syntaxnet::Parameter* add_parameter();
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::Parameter >*
      mutable_parameter();
  const ::google::protobuf::RepeatedPtrField< ::syntaxnet::Parameter >&
      parameter() const;

  // repeated .syntaxnet.FeatureFunctionDescriptor feature = 7;
  int feature_size() const;
  void clear_feature();
  static const int kFeatureFieldNumber = 7;
  const ::syntaxnet::FeatureFunctionDescriptor& feature(int index) const;
  ::syntaxnet::FeatureFunctionDescriptor* mutable_feature(int index);
  ::syntaxnet::FeatureFunctionDescriptor* add_feature();
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >*
      mutable_feature();
  const ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >&
      feature() const;

  // required string type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 argument = 3 [default = 0];
  bool has_argument() const;
  void clear_argument();
  static const int kArgumentFieldNumber = 3;
  ::google::protobuf::int32 argument() const;
  void set_argument(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:syntaxnet.FeatureFunctionDescriptor)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_name();
  void clear_has_name();
  void set_has_argument();
  void clear_has_argument();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::Parameter > parameter_;
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor > feature_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 argument_;
  friend struct  protobuf_syntaxnet_2ffeature_5fextractor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FeatureExtractorDescriptor : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:syntaxnet.FeatureExtractorDescriptor) */ {
 public:
  FeatureExtractorDescriptor();
  virtual ~FeatureExtractorDescriptor();

  FeatureExtractorDescriptor(const FeatureExtractorDescriptor& from);

  inline FeatureExtractorDescriptor& operator=(const FeatureExtractorDescriptor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FeatureExtractorDescriptor& default_instance();

  static inline const FeatureExtractorDescriptor* internal_default_instance() {
    return reinterpret_cast<const FeatureExtractorDescriptor*>(
               &_FeatureExtractorDescriptor_default_instance_);
  }

  void Swap(FeatureExtractorDescriptor* other);

  // implements Message ----------------------------------------------

  inline FeatureExtractorDescriptor* New() const PROTOBUF_FINAL { return New(NULL); }

  FeatureExtractorDescriptor* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FeatureExtractorDescriptor& from);
  void MergeFrom(const FeatureExtractorDescriptor& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FeatureExtractorDescriptor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .syntaxnet.FeatureFunctionDescriptor feature = 1;
  int feature_size() const;
  void clear_feature();
  static const int kFeatureFieldNumber = 1;
  const ::syntaxnet::FeatureFunctionDescriptor& feature(int index) const;
  ::syntaxnet::FeatureFunctionDescriptor* mutable_feature(int index);
  ::syntaxnet::FeatureFunctionDescriptor* add_feature();
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >*
      mutable_feature();
  const ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >&
      feature() const;

  // @@protoc_insertion_point(class_scope:syntaxnet.FeatureExtractorDescriptor)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor > feature_;
  friend struct  protobuf_syntaxnet_2ffeature_5fextractor_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Parameter

// optional string name = 1;
inline bool Parameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Parameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Parameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Parameter::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Parameter::name() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Parameter.name)
  return name_.GetNoArena();
}
inline void Parameter::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Parameter.name)
}
#if LANG_CXX11
inline void Parameter::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Parameter.name)
}
#endif
inline void Parameter::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Parameter.name)
}
inline void Parameter::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Parameter.name)
}
inline ::std::string* Parameter::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Parameter.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Parameter::release_name() {
  // @@protoc_insertion_point(field_release:syntaxnet.Parameter.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Parameter::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Parameter.name)
}

// optional string value = 2;
inline bool Parameter::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Parameter::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Parameter::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Parameter::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Parameter::value() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Parameter.value)
  return value_.GetNoArena();
}
inline void Parameter::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Parameter.value)
}
#if LANG_CXX11
inline void Parameter::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Parameter.value)
}
#endif
inline void Parameter::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Parameter.value)
}
inline void Parameter::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Parameter.value)
}
inline ::std::string* Parameter::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Parameter.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Parameter::release_value() {
  // @@protoc_insertion_point(field_release:syntaxnet.Parameter.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Parameter::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Parameter.value)
}

// -------------------------------------------------------------------

// FeatureFunctionDescriptor

// required string type = 1;
inline bool FeatureFunctionDescriptor::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FeatureFunctionDescriptor::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FeatureFunctionDescriptor::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FeatureFunctionDescriptor::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& FeatureFunctionDescriptor::type() const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureFunctionDescriptor.type)
  return type_.GetNoArena();
}
inline void FeatureFunctionDescriptor::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.FeatureFunctionDescriptor.type)
}
#if LANG_CXX11
inline void FeatureFunctionDescriptor::set_type(::std::string&& value) {
  set_has_type();
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.FeatureFunctionDescriptor.type)
}
#endif
inline void FeatureFunctionDescriptor::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.FeatureFunctionDescriptor.type)
}
inline void FeatureFunctionDescriptor::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.FeatureFunctionDescriptor.type)
}
inline ::std::string* FeatureFunctionDescriptor::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:syntaxnet.FeatureFunctionDescriptor.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FeatureFunctionDescriptor::release_type() {
  // @@protoc_insertion_point(field_release:syntaxnet.FeatureFunctionDescriptor.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FeatureFunctionDescriptor::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.FeatureFunctionDescriptor.type)
}

// optional string name = 2;
inline bool FeatureFunctionDescriptor::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FeatureFunctionDescriptor::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FeatureFunctionDescriptor::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FeatureFunctionDescriptor::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& FeatureFunctionDescriptor::name() const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureFunctionDescriptor.name)
  return name_.GetNoArena();
}
inline void FeatureFunctionDescriptor::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.FeatureFunctionDescriptor.name)
}
#if LANG_CXX11
inline void FeatureFunctionDescriptor::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.FeatureFunctionDescriptor.name)
}
#endif
inline void FeatureFunctionDescriptor::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.FeatureFunctionDescriptor.name)
}
inline void FeatureFunctionDescriptor::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.FeatureFunctionDescriptor.name)
}
inline ::std::string* FeatureFunctionDescriptor::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:syntaxnet.FeatureFunctionDescriptor.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FeatureFunctionDescriptor::release_name() {
  // @@protoc_insertion_point(field_release:syntaxnet.FeatureFunctionDescriptor.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FeatureFunctionDescriptor::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.FeatureFunctionDescriptor.name)
}

// optional int32 argument = 3 [default = 0];
inline bool FeatureFunctionDescriptor::has_argument() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FeatureFunctionDescriptor::set_has_argument() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FeatureFunctionDescriptor::clear_has_argument() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FeatureFunctionDescriptor::clear_argument() {
  argument_ = 0;
  clear_has_argument();
}
inline ::google::protobuf::int32 FeatureFunctionDescriptor::argument() const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureFunctionDescriptor.argument)
  return argument_;
}
inline void FeatureFunctionDescriptor::set_argument(::google::protobuf::int32 value) {
  set_has_argument();
  argument_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.FeatureFunctionDescriptor.argument)
}

// repeated .syntaxnet.Parameter parameter = 4;
inline int FeatureFunctionDescriptor::parameter_size() const {
  return parameter_.size();
}
inline void FeatureFunctionDescriptor::clear_parameter() {
  parameter_.Clear();
}
inline const ::syntaxnet::Parameter& FeatureFunctionDescriptor::parameter(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureFunctionDescriptor.parameter)
  return parameter_.Get(index);
}
inline ::syntaxnet::Parameter* FeatureFunctionDescriptor::mutable_parameter(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.FeatureFunctionDescriptor.parameter)
  return parameter_.Mutable(index);
}
inline ::syntaxnet::Parameter* FeatureFunctionDescriptor::add_parameter() {
  // @@protoc_insertion_point(field_add:syntaxnet.FeatureFunctionDescriptor.parameter)
  return parameter_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::syntaxnet::Parameter >*
FeatureFunctionDescriptor::mutable_parameter() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.FeatureFunctionDescriptor.parameter)
  return &parameter_;
}
inline const ::google::protobuf::RepeatedPtrField< ::syntaxnet::Parameter >&
FeatureFunctionDescriptor::parameter() const {
  // @@protoc_insertion_point(field_list:syntaxnet.FeatureFunctionDescriptor.parameter)
  return parameter_;
}

// repeated .syntaxnet.FeatureFunctionDescriptor feature = 7;
inline int FeatureFunctionDescriptor::feature_size() const {
  return feature_.size();
}
inline void FeatureFunctionDescriptor::clear_feature() {
  feature_.Clear();
}
inline const ::syntaxnet::FeatureFunctionDescriptor& FeatureFunctionDescriptor::feature(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureFunctionDescriptor.feature)
  return feature_.Get(index);
}
inline ::syntaxnet::FeatureFunctionDescriptor* FeatureFunctionDescriptor::mutable_feature(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.FeatureFunctionDescriptor.feature)
  return feature_.Mutable(index);
}
inline ::syntaxnet::FeatureFunctionDescriptor* FeatureFunctionDescriptor::add_feature() {
  // @@protoc_insertion_point(field_add:syntaxnet.FeatureFunctionDescriptor.feature)
  return feature_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >*
FeatureFunctionDescriptor::mutable_feature() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.FeatureFunctionDescriptor.feature)
  return &feature_;
}
inline const ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >&
FeatureFunctionDescriptor::feature() const {
  // @@protoc_insertion_point(field_list:syntaxnet.FeatureFunctionDescriptor.feature)
  return feature_;
}

// -------------------------------------------------------------------

// FeatureExtractorDescriptor

// repeated .syntaxnet.FeatureFunctionDescriptor feature = 1;
inline int FeatureExtractorDescriptor::feature_size() const {
  return feature_.size();
}
inline void FeatureExtractorDescriptor::clear_feature() {
  feature_.Clear();
}
inline const ::syntaxnet::FeatureFunctionDescriptor& FeatureExtractorDescriptor::feature(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.FeatureExtractorDescriptor.feature)
  return feature_.Get(index);
}
inline ::syntaxnet::FeatureFunctionDescriptor* FeatureExtractorDescriptor::mutable_feature(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.FeatureExtractorDescriptor.feature)
  return feature_.Mutable(index);
}
inline ::syntaxnet::FeatureFunctionDescriptor* FeatureExtractorDescriptor::add_feature() {
  // @@protoc_insertion_point(field_add:syntaxnet.FeatureExtractorDescriptor.feature)
  return feature_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >*
FeatureExtractorDescriptor::mutable_feature() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.FeatureExtractorDescriptor.feature)
  return &feature_;
}
inline const ::google::protobuf::RepeatedPtrField< ::syntaxnet::FeatureFunctionDescriptor >&
FeatureExtractorDescriptor::feature() const {
  // @@protoc_insertion_point(field_list:syntaxnet.FeatureExtractorDescriptor.feature)
  return feature_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_syntaxnet_2ffeature_5fextractor_2eproto__INCLUDED
