// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/kbest_syntax.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "syntaxnet/kbest_syntax.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace syntaxnet {
class KBestSyntaxAnalysesDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<KBestSyntaxAnalyses> {
} _KBestSyntaxAnalyses_default_instance_;
class KBestSyntaxAnalysesForSentenceDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<KBestSyntaxAnalysesForSentence> {
} _KBestSyntaxAnalysesForSentence_default_instance_;
class KBestSyntaxAnalysesForTokenDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<KBestSyntaxAnalysesForToken> {
} _KBestSyntaxAnalysesForToken_default_instance_;
class AlternativeTokenAnalysisDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<AlternativeTokenAnalysis> {
} _AlternativeTokenAnalysis_default_instance_;

namespace protobuf_syntaxnet_2fkbest_5fsyntax_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalyses, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalyses, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalyses, sentence_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalyses, token_),
  ~0u,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForSentence, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForSentence, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForSentence, start_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForSentence, end_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForSentence, token_analysis_),
  0,
  1,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForToken, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForToken, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KBestSyntaxAnalysesForToken, token_analysis_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, head_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, tag_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, category_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AlternativeTokenAnalysis, score_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(KBestSyntaxAnalyses)},
  { 8, 15, sizeof(KBestSyntaxAnalysesForSentence)},
  { 18, 23, sizeof(KBestSyntaxAnalysesForToken)},
  { 24, 33, sizeof(AlternativeTokenAnalysis)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_KBestSyntaxAnalyses_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_KBestSyntaxAnalysesForSentence_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_KBestSyntaxAnalysesForToken_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AlternativeTokenAnalysis_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "syntaxnet/kbest_syntax.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _KBestSyntaxAnalyses_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _KBestSyntaxAnalysesForSentence_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _KBestSyntaxAnalysesForToken_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _AlternativeTokenAnalysis_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::syntaxnet::protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  _KBestSyntaxAnalyses_default_instance_.DefaultConstruct();
  _KBestSyntaxAnalysesForSentence_default_instance_.DefaultConstruct();
  _KBestSyntaxAnalysesForToken_default_instance_.DefaultConstruct();
  _AlternativeTokenAnalysis_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    ::syntaxnet::Sentence::internal_default_instance(),
    60366242, 11, false, false,
    ::syntaxnet::KBestSyntaxAnalyses::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\034syntaxnet/kbest_syntax.proto\022\tsyntaxne"
      "t\032\030syntaxnet/sentence.proto\"\324\001\n\023KBestSyn"
      "taxAnalyses\022;\n\010sentence\030\001 \003(\0132).syntaxne"
      "t.KBestSyntaxAnalysesForSentence\0225\n\005toke"
      "n\030\002 \003(\0132&.syntaxnet.KBestSyntaxAnalysesF"
      "orToken2I\n\textension\022\023.syntaxnet.Sentenc"
      "e\030\242\273\344\034 \001(\0132\036.syntaxnet.KBestSyntaxAnalys"
      "es\"\201\001\n\036KBestSyntaxAnalysesForSentence\022\021\n"
      "\005start\030\001 \001(\005:\002-1\022\017\n\003end\030\002 \001(\005:\002-1\022;\n\016tok"
      "en_analysis\030\003 \003(\0132#.syntaxnet.Alternativ"
      "eTokenAnalysis\"Z\n\033KBestSyntaxAnalysesFor"
      "Token\022;\n\016token_analysis\030\003 \003(\0132#.syntaxne"
      "t.AlternativeTokenAnalysis\"e\n\030Alternativ"
      "eTokenAnalysis\022\014\n\004head\030\001 \003(\005\022\013\n\003tag\030\002 \003("
      "\t\022\020\n\010category\030\003 \003(\t\022\r\n\005label\030\004 \003(\t\022\r\n\005sc"
      "ore\030\005 \001(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 609);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "syntaxnet/kbest_syntax.proto", &protobuf_RegisterTypes);
  ::syntaxnet::protobuf_syntaxnet_2fsentence_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_syntaxnet_2fkbest_5fsyntax_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KBestSyntaxAnalyses::kSentenceFieldNumber;
const int KBestSyntaxAnalyses::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KBestSyntaxAnalyses::KBestSyntaxAnalyses()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.KBestSyntaxAnalyses)
}
KBestSyntaxAnalyses::KBestSyntaxAnalyses(const KBestSyntaxAnalyses& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      sentence_(from.sentence_),
      token_(from.token_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.KBestSyntaxAnalyses)
}

void KBestSyntaxAnalyses::SharedCtor() {
  _cached_size_ = 0;
}

KBestSyntaxAnalyses::~KBestSyntaxAnalyses() {
  // @@protoc_insertion_point(destructor:syntaxnet.KBestSyntaxAnalyses)
  SharedDtor();
}

void KBestSyntaxAnalyses::SharedDtor() {
}

void KBestSyntaxAnalyses::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KBestSyntaxAnalyses::descriptor() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[0].descriptor;
}

const KBestSyntaxAnalyses& KBestSyntaxAnalyses::default_instance() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  return *internal_default_instance();
}

KBestSyntaxAnalyses* KBestSyntaxAnalyses::New(::google::protobuf::Arena* arena) const {
  KBestSyntaxAnalyses* n = new KBestSyntaxAnalyses;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KBestSyntaxAnalyses::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.KBestSyntaxAnalyses)
  sentence_.Clear();
  token_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool KBestSyntaxAnalyses::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.KBestSyntaxAnalyses)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .syntaxnet.KBestSyntaxAnalysesForSentence sentence = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_sentence()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .syntaxnet.KBestSyntaxAnalysesForToken token = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_token()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.KBestSyntaxAnalyses)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.KBestSyntaxAnalyses)
  return false;
#undef DO_
}

void KBestSyntaxAnalyses::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.KBestSyntaxAnalyses)
  // repeated .syntaxnet.KBestSyntaxAnalysesForSentence sentence = 1;
  for (unsigned int i = 0, n = this->sentence_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->sentence(i), output);
  }

  // repeated .syntaxnet.KBestSyntaxAnalysesForToken token = 2;
  for (unsigned int i = 0, n = this->token_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->token(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.KBestSyntaxAnalyses)
}

::google::protobuf::uint8* KBestSyntaxAnalyses::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.KBestSyntaxAnalyses)
  // repeated .syntaxnet.KBestSyntaxAnalysesForSentence sentence = 1;
  for (unsigned int i = 0, n = this->sentence_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->sentence(i), false, target);
  }

  // repeated .syntaxnet.KBestSyntaxAnalysesForToken token = 2;
  for (unsigned int i = 0, n = this->token_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->token(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.KBestSyntaxAnalyses)
  return target;
}

size_t KBestSyntaxAnalyses::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.KBestSyntaxAnalyses)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.KBestSyntaxAnalysesForSentence sentence = 1;
  {
    unsigned int count = this->sentence_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->sentence(i));
    }
  }

  // repeated .syntaxnet.KBestSyntaxAnalysesForToken token = 2;
  {
    unsigned int count = this->token_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->token(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KBestSyntaxAnalyses::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.KBestSyntaxAnalyses)
  GOOGLE_DCHECK_NE(&from, this);
  const KBestSyntaxAnalyses* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KBestSyntaxAnalyses>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.KBestSyntaxAnalyses)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.KBestSyntaxAnalyses)
    MergeFrom(*source);
  }
}

void KBestSyntaxAnalyses::MergeFrom(const KBestSyntaxAnalyses& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.KBestSyntaxAnalyses)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sentence_.MergeFrom(from.sentence_);
  token_.MergeFrom(from.token_);
}

void KBestSyntaxAnalyses::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.KBestSyntaxAnalyses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KBestSyntaxAnalyses::CopyFrom(const KBestSyntaxAnalyses& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.KBestSyntaxAnalyses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KBestSyntaxAnalyses::IsInitialized() const {
  return true;
}

void KBestSyntaxAnalyses::Swap(KBestSyntaxAnalyses* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KBestSyntaxAnalyses::InternalSwap(KBestSyntaxAnalyses* other) {
  sentence_.UnsafeArenaSwap(&other->sentence_);
  token_.UnsafeArenaSwap(&other->token_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KBestSyntaxAnalyses::GetMetadata() const {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KBestSyntaxAnalyses

// repeated .syntaxnet.KBestSyntaxAnalysesForSentence sentence = 1;
int KBestSyntaxAnalyses::sentence_size() const {
  return sentence_.size();
}
void KBestSyntaxAnalyses::clear_sentence() {
  sentence_.Clear();
}
const ::syntaxnet::KBestSyntaxAnalysesForSentence& KBestSyntaxAnalyses::sentence(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalyses.sentence)
  return sentence_.Get(index);
}
::syntaxnet::KBestSyntaxAnalysesForSentence* KBestSyntaxAnalyses::mutable_sentence(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.KBestSyntaxAnalyses.sentence)
  return sentence_.Mutable(index);
}
::syntaxnet::KBestSyntaxAnalysesForSentence* KBestSyntaxAnalyses::add_sentence() {
  // @@protoc_insertion_point(field_add:syntaxnet.KBestSyntaxAnalyses.sentence)
  return sentence_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::KBestSyntaxAnalysesForSentence >*
KBestSyntaxAnalyses::mutable_sentence() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.KBestSyntaxAnalyses.sentence)
  return &sentence_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::KBestSyntaxAnalysesForSentence >&
KBestSyntaxAnalyses::sentence() const {
  // @@protoc_insertion_point(field_list:syntaxnet.KBestSyntaxAnalyses.sentence)
  return sentence_;
}

// repeated .syntaxnet.KBestSyntaxAnalysesForToken token = 2;
int KBestSyntaxAnalyses::token_size() const {
  return token_.size();
}
void KBestSyntaxAnalyses::clear_token() {
  token_.Clear();
}
const ::syntaxnet::KBestSyntaxAnalysesForToken& KBestSyntaxAnalyses::token(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalyses.token)
  return token_.Get(index);
}
::syntaxnet::KBestSyntaxAnalysesForToken* KBestSyntaxAnalyses::mutable_token(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.KBestSyntaxAnalyses.token)
  return token_.Mutable(index);
}
::syntaxnet::KBestSyntaxAnalysesForToken* KBestSyntaxAnalyses::add_token() {
  // @@protoc_insertion_point(field_add:syntaxnet.KBestSyntaxAnalyses.token)
  return token_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::KBestSyntaxAnalysesForToken >*
KBestSyntaxAnalyses::mutable_token() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.KBestSyntaxAnalyses.token)
  return &token_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::KBestSyntaxAnalysesForToken >&
KBestSyntaxAnalyses::token() const {
  // @@protoc_insertion_point(field_list:syntaxnet.KBestSyntaxAnalyses.token)
  return token_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KBestSyntaxAnalysesForSentence::kStartFieldNumber;
const int KBestSyntaxAnalysesForSentence::kEndFieldNumber;
const int KBestSyntaxAnalysesForSentence::kTokenAnalysisFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KBestSyntaxAnalysesForSentence::KBestSyntaxAnalysesForSentence()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.KBestSyntaxAnalysesForSentence)
}
KBestSyntaxAnalysesForSentence::KBestSyntaxAnalysesForSentence(const KBestSyntaxAnalysesForSentence& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      token_analysis_(from.token_analysis_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&start_, &from.start_,
    reinterpret_cast<char*>(&end_) -
    reinterpret_cast<char*>(&start_) + sizeof(end_));
  // @@protoc_insertion_point(copy_constructor:syntaxnet.KBestSyntaxAnalysesForSentence)
}

void KBestSyntaxAnalysesForSentence::SharedCtor() {
  _cached_size_ = 0;
  start_ = -1;
  end_ = -1;
}

KBestSyntaxAnalysesForSentence::~KBestSyntaxAnalysesForSentence() {
  // @@protoc_insertion_point(destructor:syntaxnet.KBestSyntaxAnalysesForSentence)
  SharedDtor();
}

void KBestSyntaxAnalysesForSentence::SharedDtor() {
}

void KBestSyntaxAnalysesForSentence::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KBestSyntaxAnalysesForSentence::descriptor() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[1].descriptor;
}

const KBestSyntaxAnalysesForSentence& KBestSyntaxAnalysesForSentence::default_instance() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  return *internal_default_instance();
}

KBestSyntaxAnalysesForSentence* KBestSyntaxAnalysesForSentence::New(::google::protobuf::Arena* arena) const {
  KBestSyntaxAnalysesForSentence* n = new KBestSyntaxAnalysesForSentence;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KBestSyntaxAnalysesForSentence::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  token_analysis_.Clear();
  if (_has_bits_[0 / 32] & 3u) {
    start_ = -1;
    end_ = -1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool KBestSyntaxAnalysesForSentence::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 start = 1 [default = -1];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_start();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &start_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 end = 2 [default = -1];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_end();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &end_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_token_analysis()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.KBestSyntaxAnalysesForSentence)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.KBestSyntaxAnalysesForSentence)
  return false;
#undef DO_
}

void KBestSyntaxAnalysesForSentence::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  // optional int32 start = 1 [default = -1];
  if (has_start()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->start(), output);
  }

  // optional int32 end = 2 [default = -1];
  if (has_end()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->end(), output);
  }

  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  for (unsigned int i = 0, n = this->token_analysis_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->token_analysis(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.KBestSyntaxAnalysesForSentence)
}

::google::protobuf::uint8* KBestSyntaxAnalysesForSentence::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  // optional int32 start = 1 [default = -1];
  if (has_start()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->start(), target);
  }

  // optional int32 end = 2 [default = -1];
  if (has_end()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->end(), target);
  }

  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  for (unsigned int i = 0, n = this->token_analysis_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->token_analysis(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.KBestSyntaxAnalysesForSentence)
  return target;
}

size_t KBestSyntaxAnalysesForSentence::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  {
    unsigned int count = this->token_analysis_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->token_analysis(i));
    }
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional int32 start = 1 [default = -1];
    if (has_start()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->start());
    }

    // optional int32 end = 2 [default = -1];
    if (has_end()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->end());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KBestSyntaxAnalysesForSentence::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  GOOGLE_DCHECK_NE(&from, this);
  const KBestSyntaxAnalysesForSentence* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KBestSyntaxAnalysesForSentence>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.KBestSyntaxAnalysesForSentence)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.KBestSyntaxAnalysesForSentence)
    MergeFrom(*source);
  }
}

void KBestSyntaxAnalysesForSentence::MergeFrom(const KBestSyntaxAnalysesForSentence& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_analysis_.MergeFrom(from.token_analysis_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_start()) {
      set_start(from.start());
    }
    if (from.has_end()) {
      set_end(from.end());
    }
  }
}

void KBestSyntaxAnalysesForSentence::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KBestSyntaxAnalysesForSentence::CopyFrom(const KBestSyntaxAnalysesForSentence& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.KBestSyntaxAnalysesForSentence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KBestSyntaxAnalysesForSentence::IsInitialized() const {
  return true;
}

void KBestSyntaxAnalysesForSentence::Swap(KBestSyntaxAnalysesForSentence* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KBestSyntaxAnalysesForSentence::InternalSwap(KBestSyntaxAnalysesForSentence* other) {
  token_analysis_.UnsafeArenaSwap(&other->token_analysis_);
  std::swap(start_, other->start_);
  std::swap(end_, other->end_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KBestSyntaxAnalysesForSentence::GetMetadata() const {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KBestSyntaxAnalysesForSentence

// optional int32 start = 1 [default = -1];
bool KBestSyntaxAnalysesForSentence::has_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void KBestSyntaxAnalysesForSentence::set_has_start() {
  _has_bits_[0] |= 0x00000001u;
}
void KBestSyntaxAnalysesForSentence::clear_has_start() {
  _has_bits_[0] &= ~0x00000001u;
}
void KBestSyntaxAnalysesForSentence::clear_start() {
  start_ = -1;
  clear_has_start();
}
::google::protobuf::int32 KBestSyntaxAnalysesForSentence::start() const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalysesForSentence.start)
  return start_;
}
void KBestSyntaxAnalysesForSentence::set_start(::google::protobuf::int32 value) {
  set_has_start();
  start_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.KBestSyntaxAnalysesForSentence.start)
}

// optional int32 end = 2 [default = -1];
bool KBestSyntaxAnalysesForSentence::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void KBestSyntaxAnalysesForSentence::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
void KBestSyntaxAnalysesForSentence::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
void KBestSyntaxAnalysesForSentence::clear_end() {
  end_ = -1;
  clear_has_end();
}
::google::protobuf::int32 KBestSyntaxAnalysesForSentence::end() const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalysesForSentence.end)
  return end_;
}
void KBestSyntaxAnalysesForSentence::set_end(::google::protobuf::int32 value) {
  set_has_end();
  end_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.KBestSyntaxAnalysesForSentence.end)
}

// repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
int KBestSyntaxAnalysesForSentence::token_analysis_size() const {
  return token_analysis_.size();
}
void KBestSyntaxAnalysesForSentence::clear_token_analysis() {
  token_analysis_.Clear();
}
const ::syntaxnet::AlternativeTokenAnalysis& KBestSyntaxAnalysesForSentence::token_analysis(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalysesForSentence.token_analysis)
  return token_analysis_.Get(index);
}
::syntaxnet::AlternativeTokenAnalysis* KBestSyntaxAnalysesForSentence::mutable_token_analysis(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.KBestSyntaxAnalysesForSentence.token_analysis)
  return token_analysis_.Mutable(index);
}
::syntaxnet::AlternativeTokenAnalysis* KBestSyntaxAnalysesForSentence::add_token_analysis() {
  // @@protoc_insertion_point(field_add:syntaxnet.KBestSyntaxAnalysesForSentence.token_analysis)
  return token_analysis_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::AlternativeTokenAnalysis >*
KBestSyntaxAnalysesForSentence::mutable_token_analysis() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.KBestSyntaxAnalysesForSentence.token_analysis)
  return &token_analysis_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::AlternativeTokenAnalysis >&
KBestSyntaxAnalysesForSentence::token_analysis() const {
  // @@protoc_insertion_point(field_list:syntaxnet.KBestSyntaxAnalysesForSentence.token_analysis)
  return token_analysis_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KBestSyntaxAnalysesForToken::kTokenAnalysisFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KBestSyntaxAnalysesForToken::KBestSyntaxAnalysesForToken()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.KBestSyntaxAnalysesForToken)
}
KBestSyntaxAnalysesForToken::KBestSyntaxAnalysesForToken(const KBestSyntaxAnalysesForToken& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      token_analysis_(from.token_analysis_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.KBestSyntaxAnalysesForToken)
}

void KBestSyntaxAnalysesForToken::SharedCtor() {
  _cached_size_ = 0;
}

KBestSyntaxAnalysesForToken::~KBestSyntaxAnalysesForToken() {
  // @@protoc_insertion_point(destructor:syntaxnet.KBestSyntaxAnalysesForToken)
  SharedDtor();
}

void KBestSyntaxAnalysesForToken::SharedDtor() {
}

void KBestSyntaxAnalysesForToken::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KBestSyntaxAnalysesForToken::descriptor() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[2].descriptor;
}

const KBestSyntaxAnalysesForToken& KBestSyntaxAnalysesForToken::default_instance() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  return *internal_default_instance();
}

KBestSyntaxAnalysesForToken* KBestSyntaxAnalysesForToken::New(::google::protobuf::Arena* arena) const {
  KBestSyntaxAnalysesForToken* n = new KBestSyntaxAnalysesForToken;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KBestSyntaxAnalysesForToken::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.KBestSyntaxAnalysesForToken)
  token_analysis_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool KBestSyntaxAnalysesForToken::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.KBestSyntaxAnalysesForToken)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_token_analysis()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.KBestSyntaxAnalysesForToken)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.KBestSyntaxAnalysesForToken)
  return false;
#undef DO_
}

void KBestSyntaxAnalysesForToken::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.KBestSyntaxAnalysesForToken)
  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  for (unsigned int i = 0, n = this->token_analysis_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->token_analysis(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.KBestSyntaxAnalysesForToken)
}

::google::protobuf::uint8* KBestSyntaxAnalysesForToken::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.KBestSyntaxAnalysesForToken)
  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  for (unsigned int i = 0, n = this->token_analysis_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->token_analysis(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.KBestSyntaxAnalysesForToken)
  return target;
}

size_t KBestSyntaxAnalysesForToken::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.KBestSyntaxAnalysesForToken)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
  {
    unsigned int count = this->token_analysis_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->token_analysis(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KBestSyntaxAnalysesForToken::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.KBestSyntaxAnalysesForToken)
  GOOGLE_DCHECK_NE(&from, this);
  const KBestSyntaxAnalysesForToken* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KBestSyntaxAnalysesForToken>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.KBestSyntaxAnalysesForToken)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.KBestSyntaxAnalysesForToken)
    MergeFrom(*source);
  }
}

void KBestSyntaxAnalysesForToken::MergeFrom(const KBestSyntaxAnalysesForToken& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.KBestSyntaxAnalysesForToken)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_analysis_.MergeFrom(from.token_analysis_);
}

void KBestSyntaxAnalysesForToken::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.KBestSyntaxAnalysesForToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KBestSyntaxAnalysesForToken::CopyFrom(const KBestSyntaxAnalysesForToken& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.KBestSyntaxAnalysesForToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KBestSyntaxAnalysesForToken::IsInitialized() const {
  return true;
}

void KBestSyntaxAnalysesForToken::Swap(KBestSyntaxAnalysesForToken* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KBestSyntaxAnalysesForToken::InternalSwap(KBestSyntaxAnalysesForToken* other) {
  token_analysis_.UnsafeArenaSwap(&other->token_analysis_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KBestSyntaxAnalysesForToken::GetMetadata() const {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KBestSyntaxAnalysesForToken

// repeated .syntaxnet.AlternativeTokenAnalysis token_analysis = 3;
int KBestSyntaxAnalysesForToken::token_analysis_size() const {
  return token_analysis_.size();
}
void KBestSyntaxAnalysesForToken::clear_token_analysis() {
  token_analysis_.Clear();
}
const ::syntaxnet::AlternativeTokenAnalysis& KBestSyntaxAnalysesForToken::token_analysis(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.KBestSyntaxAnalysesForToken.token_analysis)
  return token_analysis_.Get(index);
}
::syntaxnet::AlternativeTokenAnalysis* KBestSyntaxAnalysesForToken::mutable_token_analysis(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.KBestSyntaxAnalysesForToken.token_analysis)
  return token_analysis_.Mutable(index);
}
::syntaxnet::AlternativeTokenAnalysis* KBestSyntaxAnalysesForToken::add_token_analysis() {
  // @@protoc_insertion_point(field_add:syntaxnet.KBestSyntaxAnalysesForToken.token_analysis)
  return token_analysis_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::AlternativeTokenAnalysis >*
KBestSyntaxAnalysesForToken::mutable_token_analysis() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.KBestSyntaxAnalysesForToken.token_analysis)
  return &token_analysis_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::AlternativeTokenAnalysis >&
KBestSyntaxAnalysesForToken::token_analysis() const {
  // @@protoc_insertion_point(field_list:syntaxnet.KBestSyntaxAnalysesForToken.token_analysis)
  return token_analysis_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AlternativeTokenAnalysis::kHeadFieldNumber;
const int AlternativeTokenAnalysis::kTagFieldNumber;
const int AlternativeTokenAnalysis::kCategoryFieldNumber;
const int AlternativeTokenAnalysis::kLabelFieldNumber;
const int AlternativeTokenAnalysis::kScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AlternativeTokenAnalysis::AlternativeTokenAnalysis()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.AlternativeTokenAnalysis)
}
AlternativeTokenAnalysis::AlternativeTokenAnalysis(const AlternativeTokenAnalysis& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      head_(from.head_),
      tag_(from.tag_),
      category_(from.category_),
      label_(from.label_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  score_ = from.score_;
  // @@protoc_insertion_point(copy_constructor:syntaxnet.AlternativeTokenAnalysis)
}

void AlternativeTokenAnalysis::SharedCtor() {
  _cached_size_ = 0;
  score_ = 0;
}

AlternativeTokenAnalysis::~AlternativeTokenAnalysis() {
  // @@protoc_insertion_point(destructor:syntaxnet.AlternativeTokenAnalysis)
  SharedDtor();
}

void AlternativeTokenAnalysis::SharedDtor() {
}

void AlternativeTokenAnalysis::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AlternativeTokenAnalysis::descriptor() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[3].descriptor;
}

const AlternativeTokenAnalysis& AlternativeTokenAnalysis::default_instance() {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::InitDefaults();
  return *internal_default_instance();
}

AlternativeTokenAnalysis* AlternativeTokenAnalysis::New(::google::protobuf::Arena* arena) const {
  AlternativeTokenAnalysis* n = new AlternativeTokenAnalysis;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AlternativeTokenAnalysis::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.AlternativeTokenAnalysis)
  head_.Clear();
  tag_.Clear();
  category_.Clear();
  label_.Clear();
  score_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AlternativeTokenAnalysis::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.AlternativeTokenAnalysis)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 head = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8u, input, this->mutable_head())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_head())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string tag = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_tag()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->tag(this->tag_size() - 1).data(),
            this->tag(this->tag_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.AlternativeTokenAnalysis.tag");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string category = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_category()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->category(this->category_size() - 1).data(),
            this->category(this->category_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.AlternativeTokenAnalysis.category");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string label = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->label(this->label_size() - 1).data(),
            this->label(this->label_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.AlternativeTokenAnalysis.label");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double score = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u)) {
          set_has_score();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.AlternativeTokenAnalysis)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.AlternativeTokenAnalysis)
  return false;
#undef DO_
}

void AlternativeTokenAnalysis::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.AlternativeTokenAnalysis)
  // repeated int32 head = 1;
  for (int i = 0, n = this->head_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->head(i), output);
  }

  // repeated string tag = 2;
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tag(i).data(), this->tag(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.tag");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->tag(i), output);
  }

  // repeated string category = 3;
  for (int i = 0, n = this->category_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->category(i).data(), this->category(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.category");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->category(i), output);
  }

  // repeated string label = 4;
  for (int i = 0, n = this->label_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->label(i).data(), this->label(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.label");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->label(i), output);
  }

  // optional double score = 5;
  if (has_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->score(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.AlternativeTokenAnalysis)
}

::google::protobuf::uint8* AlternativeTokenAnalysis::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.AlternativeTokenAnalysis)
  // repeated int32 head = 1;
  for (int i = 0, n = this->head_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->head(i), target);
  }

  // repeated string tag = 2;
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tag(i).data(), this->tag(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.tag");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->tag(i), target);
  }

  // repeated string category = 3;
  for (int i = 0, n = this->category_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->category(i).data(), this->category(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.category");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->category(i), target);
  }

  // repeated string label = 4;
  for (int i = 0, n = this->label_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->label(i).data(), this->label(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.AlternativeTokenAnalysis.label");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->label(i), target);
  }

  // optional double score = 5;
  if (has_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->score(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.AlternativeTokenAnalysis)
  return target;
}

size_t AlternativeTokenAnalysis::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.AlternativeTokenAnalysis)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated int32 head = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->head_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->head_size());
    total_size += data_size;
  }

  // repeated string tag = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->tag_size());
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->tag(i));
  }

  // repeated string category = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->category_size());
  for (int i = 0, n = this->category_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->category(i));
  }

  // repeated string label = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->label_size());
  for (int i = 0, n = this->label_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->label(i));
  }

  // optional double score = 5;
  if (has_score()) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AlternativeTokenAnalysis::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.AlternativeTokenAnalysis)
  GOOGLE_DCHECK_NE(&from, this);
  const AlternativeTokenAnalysis* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AlternativeTokenAnalysis>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.AlternativeTokenAnalysis)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.AlternativeTokenAnalysis)
    MergeFrom(*source);
  }
}

void AlternativeTokenAnalysis::MergeFrom(const AlternativeTokenAnalysis& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.AlternativeTokenAnalysis)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  head_.MergeFrom(from.head_);
  tag_.MergeFrom(from.tag_);
  category_.MergeFrom(from.category_);
  label_.MergeFrom(from.label_);
  if (from.has_score()) {
    set_score(from.score());
  }
}

void AlternativeTokenAnalysis::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.AlternativeTokenAnalysis)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AlternativeTokenAnalysis::CopyFrom(const AlternativeTokenAnalysis& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.AlternativeTokenAnalysis)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AlternativeTokenAnalysis::IsInitialized() const {
  return true;
}

void AlternativeTokenAnalysis::Swap(AlternativeTokenAnalysis* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AlternativeTokenAnalysis::InternalSwap(AlternativeTokenAnalysis* other) {
  head_.UnsafeArenaSwap(&other->head_);
  tag_.UnsafeArenaSwap(&other->tag_);
  category_.UnsafeArenaSwap(&other->category_);
  label_.UnsafeArenaSwap(&other->label_);
  std::swap(score_, other->score_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AlternativeTokenAnalysis::GetMetadata() const {
  protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fkbest_5fsyntax_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AlternativeTokenAnalysis

// repeated int32 head = 1;
int AlternativeTokenAnalysis::head_size() const {
  return head_.size();
}
void AlternativeTokenAnalysis::clear_head() {
  head_.Clear();
}
::google::protobuf::int32 AlternativeTokenAnalysis::head(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.AlternativeTokenAnalysis.head)
  return head_.Get(index);
}
void AlternativeTokenAnalysis::set_head(int index, ::google::protobuf::int32 value) {
  head_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.head)
}
void AlternativeTokenAnalysis::add_head(::google::protobuf::int32 value) {
  head_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.head)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AlternativeTokenAnalysis::head() const {
  // @@protoc_insertion_point(field_list:syntaxnet.AlternativeTokenAnalysis.head)
  return head_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AlternativeTokenAnalysis::mutable_head() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.AlternativeTokenAnalysis.head)
  return &head_;
}

// repeated string tag = 2;
int AlternativeTokenAnalysis::tag_size() const {
  return tag_.size();
}
void AlternativeTokenAnalysis::clear_tag() {
  tag_.Clear();
}
const ::std::string& AlternativeTokenAnalysis::tag(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.AlternativeTokenAnalysis.tag)
  return tag_.Get(index);
}
::std::string* AlternativeTokenAnalysis::mutable_tag(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.AlternativeTokenAnalysis.tag)
  return tag_.Mutable(index);
}
void AlternativeTokenAnalysis::set_tag(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.tag)
  tag_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void AlternativeTokenAnalysis::set_tag(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.tag)
  tag_.Mutable(index)->assign(std::move(value));
}
#endif
void AlternativeTokenAnalysis::set_tag(int index, const char* value) {
  tag_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.AlternativeTokenAnalysis.tag)
}
void AlternativeTokenAnalysis::set_tag(int index, const char* value, size_t size) {
  tag_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.AlternativeTokenAnalysis.tag)
}
::std::string* AlternativeTokenAnalysis::add_tag() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.AlternativeTokenAnalysis.tag)
  return tag_.Add();
}
void AlternativeTokenAnalysis::add_tag(const ::std::string& value) {
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.tag)
}
#if LANG_CXX11
void AlternativeTokenAnalysis::add_tag(::std::string&& value) {
  tag_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.tag)
}
#endif
void AlternativeTokenAnalysis::add_tag(const char* value) {
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.AlternativeTokenAnalysis.tag)
}
void AlternativeTokenAnalysis::add_tag(const char* value, size_t size) {
  tag_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.AlternativeTokenAnalysis.tag)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
AlternativeTokenAnalysis::tag() const {
  // @@protoc_insertion_point(field_list:syntaxnet.AlternativeTokenAnalysis.tag)
  return tag_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
AlternativeTokenAnalysis::mutable_tag() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.AlternativeTokenAnalysis.tag)
  return &tag_;
}

// repeated string category = 3;
int AlternativeTokenAnalysis::category_size() const {
  return category_.size();
}
void AlternativeTokenAnalysis::clear_category() {
  category_.Clear();
}
const ::std::string& AlternativeTokenAnalysis::category(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.AlternativeTokenAnalysis.category)
  return category_.Get(index);
}
::std::string* AlternativeTokenAnalysis::mutable_category(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.AlternativeTokenAnalysis.category)
  return category_.Mutable(index);
}
void AlternativeTokenAnalysis::set_category(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.category)
  category_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void AlternativeTokenAnalysis::set_category(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.category)
  category_.Mutable(index)->assign(std::move(value));
}
#endif
void AlternativeTokenAnalysis::set_category(int index, const char* value) {
  category_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.AlternativeTokenAnalysis.category)
}
void AlternativeTokenAnalysis::set_category(int index, const char* value, size_t size) {
  category_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.AlternativeTokenAnalysis.category)
}
::std::string* AlternativeTokenAnalysis::add_category() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.AlternativeTokenAnalysis.category)
  return category_.Add();
}
void AlternativeTokenAnalysis::add_category(const ::std::string& value) {
  category_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.category)
}
#if LANG_CXX11
void AlternativeTokenAnalysis::add_category(::std::string&& value) {
  category_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.category)
}
#endif
void AlternativeTokenAnalysis::add_category(const char* value) {
  category_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.AlternativeTokenAnalysis.category)
}
void AlternativeTokenAnalysis::add_category(const char* value, size_t size) {
  category_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.AlternativeTokenAnalysis.category)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
AlternativeTokenAnalysis::category() const {
  // @@protoc_insertion_point(field_list:syntaxnet.AlternativeTokenAnalysis.category)
  return category_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
AlternativeTokenAnalysis::mutable_category() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.AlternativeTokenAnalysis.category)
  return &category_;
}

// repeated string label = 4;
int AlternativeTokenAnalysis::label_size() const {
  return label_.size();
}
void AlternativeTokenAnalysis::clear_label() {
  label_.Clear();
}
const ::std::string& AlternativeTokenAnalysis::label(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.AlternativeTokenAnalysis.label)
  return label_.Get(index);
}
::std::string* AlternativeTokenAnalysis::mutable_label(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.AlternativeTokenAnalysis.label)
  return label_.Mutable(index);
}
void AlternativeTokenAnalysis::set_label(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.label)
  label_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void AlternativeTokenAnalysis::set_label(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.label)
  label_.Mutable(index)->assign(std::move(value));
}
#endif
void AlternativeTokenAnalysis::set_label(int index, const char* value) {
  label_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.AlternativeTokenAnalysis.label)
}
void AlternativeTokenAnalysis::set_label(int index, const char* value, size_t size) {
  label_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.AlternativeTokenAnalysis.label)
}
::std::string* AlternativeTokenAnalysis::add_label() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.AlternativeTokenAnalysis.label)
  return label_.Add();
}
void AlternativeTokenAnalysis::add_label(const ::std::string& value) {
  label_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.label)
}
#if LANG_CXX11
void AlternativeTokenAnalysis::add_label(::std::string&& value) {
  label_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.AlternativeTokenAnalysis.label)
}
#endif
void AlternativeTokenAnalysis::add_label(const char* value) {
  label_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.AlternativeTokenAnalysis.label)
}
void AlternativeTokenAnalysis::add_label(const char* value, size_t size) {
  label_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.AlternativeTokenAnalysis.label)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
AlternativeTokenAnalysis::label() const {
  // @@protoc_insertion_point(field_list:syntaxnet.AlternativeTokenAnalysis.label)
  return label_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
AlternativeTokenAnalysis::mutable_label() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.AlternativeTokenAnalysis.label)
  return &label_;
}

// optional double score = 5;
bool AlternativeTokenAnalysis::has_score() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AlternativeTokenAnalysis::set_has_score() {
  _has_bits_[0] |= 0x00000001u;
}
void AlternativeTokenAnalysis::clear_has_score() {
  _has_bits_[0] &= ~0x00000001u;
}
void AlternativeTokenAnalysis::clear_score() {
  score_ = 0;
  clear_has_score();
}
double AlternativeTokenAnalysis::score() const {
  // @@protoc_insertion_point(field_get:syntaxnet.AlternativeTokenAnalysis.score)
  return score_;
}
void AlternativeTokenAnalysis::set_score(double value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.AlternativeTokenAnalysis.score)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KBestSyntaxAnalyses::kExtensionFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::syntaxnet::Sentence,
    ::google::protobuf::internal::MessageTypeTraits< ::syntaxnet::KBestSyntaxAnalyses >, 11, false >
  KBestSyntaxAnalyses::extension(kExtensionFieldNumber, *::syntaxnet::KBestSyntaxAnalyses::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)
