// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/sentence.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "syntaxnet/sentence.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace syntaxnet {
class SentenceDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Sentence> {
} _Sentence_default_instance_;
class TokenDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Token> {
} _Token_default_instance_;
class TokenMorphology_AttributeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TokenMorphology_Attribute> {
} _TokenMorphology_Attribute_default_instance_;
class TokenMorphologyDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TokenMorphology> {
} _TokenMorphology_default_instance_;

namespace protobuf_syntaxnet_2fsentence_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, _internal_metadata_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, _extensions_),
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, docid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, text_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sentence, token_),
  0,
  1,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, _internal_metadata_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, _extensions_),
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, word_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, start_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, end_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, head_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, tag_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, category_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Token, break_level_),
  0,
  4,
  5,
  6,
  1,
  2,
  3,
  7,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology_Attribute, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology_Attribute, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology_Attribute, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology_Attribute, value_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenMorphology, attribute_),
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(Sentence)},
  { 10, 22, sizeof(Token)},
  { 30, 36, sizeof(TokenMorphology_Attribute)},
  { 38, 43, sizeof(TokenMorphology)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Sentence_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Token_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TokenMorphology_Attribute_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TokenMorphology_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "syntaxnet/sentence.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _Sentence_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Token_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _TokenMorphology_Attribute_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _TokenMorphology_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Sentence_default_instance_.DefaultConstruct();
  _Token_default_instance_.DefaultConstruct();
  _TokenMorphology_Attribute_default_instance_.DefaultConstruct();
  _TokenMorphology_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    ::syntaxnet::Token::internal_default_instance(),
    63949837, 11, false, false,
    ::syntaxnet::TokenMorphology::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030syntaxnet/sentence.proto\022\tsyntaxnet\"S\n"
      "\010Sentence\022\r\n\005docid\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\022\037"
      "\n\005token\030\003 \003(\0132\020.syntaxnet.Token*\t\010\350\007\020\200\200\200"
      "\200\002\"\214\002\n\005Token\022\014\n\004word\030\001 \002(\t\022\r\n\005start\030\002 \002("
      "\005\022\013\n\003end\030\003 \002(\005\022\020\n\004head\030\004 \001(\005:\002-1\022\013\n\003tag\030"
      "\005 \001(\t\022\020\n\010category\030\006 \001(\t\022\r\n\005label\030\007 \001(\t\022="
      "\n\013break_level\030\010 \001(\0162\033.syntaxnet.Token.Br"
      "eakLevel:\013SPACE_BREAK\"O\n\nBreakLevel\022\014\n\010N"
      "O_BREAK\020\000\022\017\n\013SPACE_BREAK\020\001\022\016\n\nLINE_BREAK"
      "\020\002\022\022\n\016SENTENCE_BREAK\020\003*\t\010\350\007\020\200\200\200\200\002\"\271\001\n\017To"
      "kenMorphology\0227\n\tattribute\030\003 \003(\0132$.synta"
      "xnet.TokenMorphology.Attribute\032(\n\tAttrib"
      "ute\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \002(\t2C\n\nmorp"
      "hology\022\020.syntaxnet.Token\030\215\230\277\036 \001(\0132\032.synt"
      "axnet.TokenMorphology"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 581);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "syntaxnet/sentence.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_syntaxnet_2fsentence_2eproto

const ::google::protobuf::EnumDescriptor* Token_BreakLevel_descriptor() {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_enum_descriptors[0];
}
bool Token_BreakLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Token_BreakLevel Token::NO_BREAK;
const Token_BreakLevel Token::SPACE_BREAK;
const Token_BreakLevel Token::LINE_BREAK;
const Token_BreakLevel Token::SENTENCE_BREAK;
const Token_BreakLevel Token::BreakLevel_MIN;
const Token_BreakLevel Token::BreakLevel_MAX;
const int Token::BreakLevel_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Sentence::kDocidFieldNumber;
const int Sentence::kTextFieldNumber;
const int Sentence::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Sentence::Sentence()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.Sentence)
}
Sentence::Sentence(const Sentence& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      token_(from.token_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _extensions_.MergeFrom(from._extensions_);
  docid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_docid()) {
    docid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.docid_);
  }
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_text()) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  // @@protoc_insertion_point(copy_constructor:syntaxnet.Sentence)
}

void Sentence::SharedCtor() {
  _cached_size_ = 0;
  docid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Sentence::~Sentence() {
  // @@protoc_insertion_point(destructor:syntaxnet.Sentence)
  SharedDtor();
}

void Sentence::SharedDtor() {
  docid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Sentence::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sentence::descriptor() {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[0].descriptor;
}

const Sentence& Sentence::default_instance() {
  protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  return *internal_default_instance();
}

Sentence* Sentence::New(::google::protobuf::Arena* arena) const {
  Sentence* n = new Sentence;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Sentence::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.Sentence)
  _extensions_.Clear();
  token_.Clear();
  if (_has_bits_[0 / 32] & 3u) {
    if (has_docid()) {
      GOOGLE_DCHECK(!docid_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*docid_.UnsafeRawStringPointer())->clear();
    }
    if (has_text()) {
      GOOGLE_DCHECK(!text_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*text_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Sentence::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.Sentence)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string docid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_docid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->docid().data(), this->docid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Sentence.docid");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string text = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->text().data(), this->text().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Sentence.text");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .syntaxnet.Token token = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_token()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, internal_default_instance(),
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.Sentence)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.Sentence)
  return false;
#undef DO_
}

void Sentence::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.Sentence)
  // optional string docid = 1;
  if (has_docid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->docid().data(), this->docid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Sentence.docid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->docid(), output);
  }

  // optional string text = 2;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Sentence.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->text(), output);
  }

  // repeated .syntaxnet.Token token = 3;
  for (unsigned int i = 0, n = this->token_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->token(i), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.Sentence)
}

::google::protobuf::uint8* Sentence::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.Sentence)
  // optional string docid = 1;
  if (has_docid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->docid().data(), this->docid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Sentence.docid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->docid(), target);
  }

  // optional string text = 2;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Sentence.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->text(), target);
  }

  // repeated .syntaxnet.Token token = 3;
  for (unsigned int i = 0, n = this->token_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->token(i), false, target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.InternalSerializeWithCachedSizesToArray(
      1000, 536870912, deterministic, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.Sentence)
  return target;
}

size_t Sentence::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.Sentence)
  size_t total_size = 0;

  total_size += _extensions_.ByteSize();

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.Token token = 3;
  {
    unsigned int count = this->token_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->token(i));
    }
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string docid = 1;
    if (has_docid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->docid());
    }

    // optional string text = 2;
    if (has_text()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->text());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sentence::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.Sentence)
  GOOGLE_DCHECK_NE(&from, this);
  const Sentence* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Sentence>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.Sentence)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.Sentence)
    MergeFrom(*source);
  }
}

void Sentence::MergeFrom(const Sentence& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.Sentence)
  GOOGLE_DCHECK_NE(&from, this);
  _extensions_.MergeFrom(from._extensions_);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_.MergeFrom(from.token_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_docid()) {
      set_has_docid();
      docid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.docid_);
    }
    if (from.has_text()) {
      set_has_text();
      text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
    }
  }
}

void Sentence::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.Sentence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sentence::CopyFrom(const Sentence& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.Sentence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sentence::IsInitialized() const {
  if (!_extensions_.IsInitialized()) {
    return false;
  }

  if (!::google::protobuf::internal::AllAreInitialized(this->token())) return false;
  return true;
}

void Sentence::Swap(Sentence* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Sentence::InternalSwap(Sentence* other) {
  token_.UnsafeArenaSwap(&other->token_);
  docid_.Swap(&other->docid_);
  text_.Swap(&other->text_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
  _extensions_.Swap(&other->_extensions_);
}

::google::protobuf::Metadata Sentence::GetMetadata() const {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Sentence

// optional string docid = 1;
bool Sentence::has_docid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Sentence::set_has_docid() {
  _has_bits_[0] |= 0x00000001u;
}
void Sentence::clear_has_docid() {
  _has_bits_[0] &= ~0x00000001u;
}
void Sentence::clear_docid() {
  docid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_docid();
}
const ::std::string& Sentence::docid() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Sentence.docid)
  return docid_.GetNoArena();
}
void Sentence::set_docid(const ::std::string& value) {
  set_has_docid();
  docid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Sentence.docid)
}
#if LANG_CXX11
void Sentence::set_docid(::std::string&& value) {
  set_has_docid();
  docid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Sentence.docid)
}
#endif
void Sentence::set_docid(const char* value) {
  set_has_docid();
  docid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Sentence.docid)
}
void Sentence::set_docid(const char* value, size_t size) {
  set_has_docid();
  docid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Sentence.docid)
}
::std::string* Sentence::mutable_docid() {
  set_has_docid();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Sentence.docid)
  return docid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Sentence::release_docid() {
  // @@protoc_insertion_point(field_release:syntaxnet.Sentence.docid)
  clear_has_docid();
  return docid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Sentence::set_allocated_docid(::std::string* docid) {
  if (docid != NULL) {
    set_has_docid();
  } else {
    clear_has_docid();
  }
  docid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), docid);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Sentence.docid)
}

// optional string text = 2;
bool Sentence::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Sentence::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
void Sentence::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
void Sentence::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
const ::std::string& Sentence::text() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Sentence.text)
  return text_.GetNoArena();
}
void Sentence::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Sentence.text)
}
#if LANG_CXX11
void Sentence::set_text(::std::string&& value) {
  set_has_text();
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Sentence.text)
}
#endif
void Sentence::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Sentence.text)
}
void Sentence::set_text(const char* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Sentence.text)
}
::std::string* Sentence::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Sentence.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Sentence::release_text() {
  // @@protoc_insertion_point(field_release:syntaxnet.Sentence.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Sentence::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Sentence.text)
}

// repeated .syntaxnet.Token token = 3;
int Sentence::token_size() const {
  return token_.size();
}
void Sentence::clear_token() {
  token_.Clear();
}
const ::syntaxnet::Token& Sentence::token(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.Sentence.token)
  return token_.Get(index);
}
::syntaxnet::Token* Sentence::mutable_token(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.Sentence.token)
  return token_.Mutable(index);
}
::syntaxnet::Token* Sentence::add_token() {
  // @@protoc_insertion_point(field_add:syntaxnet.Sentence.token)
  return token_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::Token >*
Sentence::mutable_token() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.Sentence.token)
  return &token_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::Token >&
Sentence::token() const {
  // @@protoc_insertion_point(field_list:syntaxnet.Sentence.token)
  return token_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Token::kWordFieldNumber;
const int Token::kStartFieldNumber;
const int Token::kEndFieldNumber;
const int Token::kHeadFieldNumber;
const int Token::kTagFieldNumber;
const int Token::kCategoryFieldNumber;
const int Token::kLabelFieldNumber;
const int Token::kBreakLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Token::Token()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.Token)
}
Token::Token(const Token& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _extensions_.MergeFrom(from._extensions_);
  word_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_word()) {
    word_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.word_);
  }
  tag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_tag()) {
    tag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tag_);
  }
  category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_category()) {
    category_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.category_);
  }
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_label()) {
    label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
  }
  ::memcpy(&start_, &from.start_,
    reinterpret_cast<char*>(&break_level_) -
    reinterpret_cast<char*>(&start_) + sizeof(break_level_));
  // @@protoc_insertion_point(copy_constructor:syntaxnet.Token)
}

void Token::SharedCtor() {
  _cached_size_ = 0;
  word_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&start_, 0, reinterpret_cast<char*>(&end_) -
    reinterpret_cast<char*>(&start_) + sizeof(end_));
  head_ = -1;
  break_level_ = 1;
}

Token::~Token() {
  // @@protoc_insertion_point(destructor:syntaxnet.Token)
  SharedDtor();
}

void Token::SharedDtor() {
  word_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tag_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  category_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  label_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Token::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Token::descriptor() {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[1].descriptor;
}

const Token& Token::default_instance() {
  protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  return *internal_default_instance();
}

Token* Token::New(::google::protobuf::Arena* arena) const {
  Token* n = new Token;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Token::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.Token)
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & 15u) {
    if (has_word()) {
      GOOGLE_DCHECK(!word_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*word_.UnsafeRawStringPointer())->clear();
    }
    if (has_tag()) {
      GOOGLE_DCHECK(!tag_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*tag_.UnsafeRawStringPointer())->clear();
    }
    if (has_category()) {
      GOOGLE_DCHECK(!category_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*category_.UnsafeRawStringPointer())->clear();
    }
    if (has_label()) {
      GOOGLE_DCHECK(!label_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*label_.UnsafeRawStringPointer())->clear();
    }
  }
  if (_has_bits_[0 / 32] & 240u) {
    ::memset(&start_, 0, reinterpret_cast<char*>(&end_) -
      reinterpret_cast<char*>(&start_) + sizeof(end_));
    head_ = -1;
    break_level_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Token::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.Token)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string word = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_word()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->word().data(), this->word().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Token.word");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 start = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_start();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &start_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 end = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_end();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &end_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 head = 4 [default = -1];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          set_has_head();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &head_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string tag = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tag()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->tag().data(), this->tag().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Token.tag");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string category = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_category()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->category().data(), this->category().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Token.category");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string label = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->label().data(), this->label().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.Token.label");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .syntaxnet.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::syntaxnet::Token_BreakLevel_IsValid(value)) {
            set_break_level(static_cast< ::syntaxnet::Token_BreakLevel >(value));
          } else {
            mutable_unknown_fields()->AddVarint(8, value);
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, internal_default_instance(),
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.Token)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.Token)
  return false;
#undef DO_
}

void Token::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.Token)
  // required string word = 1;
  if (has_word()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->word().data(), this->word().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.word");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->word(), output);
  }

  // required int32 start = 2;
  if (has_start()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->start(), output);
  }

  // required int32 end = 3;
  if (has_end()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->end(), output);
  }

  // optional int32 head = 4 [default = -1];
  if (has_head()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->head(), output);
  }

  // optional string tag = 5;
  if (has_tag()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tag().data(), this->tag().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.tag");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->tag(), output);
  }

  // optional string category = 6;
  if (has_category()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->category().data(), this->category().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.category");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->category(), output);
  }

  // optional string label = 7;
  if (has_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->label(), output);
  }

  // optional .syntaxnet.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
  if (has_break_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      8, this->break_level(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.Token)
}

::google::protobuf::uint8* Token::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.Token)
  // required string word = 1;
  if (has_word()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->word().data(), this->word().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.word");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->word(), target);
  }

  // required int32 start = 2;
  if (has_start()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->start(), target);
  }

  // required int32 end = 3;
  if (has_end()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->end(), target);
  }

  // optional int32 head = 4 [default = -1];
  if (has_head()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->head(), target);
  }

  // optional string tag = 5;
  if (has_tag()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tag().data(), this->tag().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.tag");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->tag(), target);
  }

  // optional string category = 6;
  if (has_category()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->category().data(), this->category().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.category");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->category(), target);
  }

  // optional string label = 7;
  if (has_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.Token.label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->label(), target);
  }

  // optional .syntaxnet.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
  if (has_break_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      8, this->break_level(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.InternalSerializeWithCachedSizesToArray(
      1000, 536870912, deterministic, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.Token)
  return target;
}

size_t Token::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:syntaxnet.Token)
  size_t total_size = 0;

  if (has_word()) {
    // required string word = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->word());
  }

  if (has_start()) {
    // required int32 start = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->start());
  }

  if (has_end()) {
    // required int32 end = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->end());
  }

  return total_size;
}
size_t Token::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.Token)
  size_t total_size = 0;

  total_size += _extensions_.ByteSize();

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000031) ^ 0x00000031) == 0) {  // All required fields are present.
    // required string word = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->word());

    // required int32 start = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->start());

    // required int32 end = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->end());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[0 / 32] & 14u) {
    // optional string tag = 5;
    if (has_tag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->tag());
    }

    // optional string category = 6;
    if (has_category()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->category());
    }

    // optional string label = 7;
    if (has_label()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->label());
    }

  }
  if (_has_bits_[0 / 32] & 192u) {
    // optional int32 head = 4 [default = -1];
    if (has_head()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->head());
    }

    // optional .syntaxnet.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
    if (has_break_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->break_level());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Token::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.Token)
  GOOGLE_DCHECK_NE(&from, this);
  const Token* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Token>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.Token)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.Token)
    MergeFrom(*source);
  }
}

void Token::MergeFrom(const Token& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.Token)
  GOOGLE_DCHECK_NE(&from, this);
  _extensions_.MergeFrom(from._extensions_);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 255u) {
    if (from.has_word()) {
      set_has_word();
      word_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.word_);
    }
    if (from.has_tag()) {
      set_has_tag();
      tag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tag_);
    }
    if (from.has_category()) {
      set_has_category();
      category_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.category_);
    }
    if (from.has_label()) {
      set_has_label();
      label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
    }
    if (from.has_start()) {
      set_start(from.start());
    }
    if (from.has_end()) {
      set_end(from.end());
    }
    if (from.has_head()) {
      set_head(from.head());
    }
    if (from.has_break_level()) {
      set_break_level(from.break_level());
    }
  }
}

void Token::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Token::CopyFrom(const Token& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Token::IsInitialized() const {
  if (!_extensions_.IsInitialized()) {
    return false;
  }

  if ((_has_bits_[0] & 0x00000031) != 0x00000031) return false;
  return true;
}

void Token::Swap(Token* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Token::InternalSwap(Token* other) {
  word_.Swap(&other->word_);
  tag_.Swap(&other->tag_);
  category_.Swap(&other->category_);
  label_.Swap(&other->label_);
  std::swap(start_, other->start_);
  std::swap(end_, other->end_);
  std::swap(head_, other->head_);
  std::swap(break_level_, other->break_level_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
  _extensions_.Swap(&other->_extensions_);
}

::google::protobuf::Metadata Token::GetMetadata() const {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Token

// required string word = 1;
bool Token::has_word() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Token::set_has_word() {
  _has_bits_[0] |= 0x00000001u;
}
void Token::clear_has_word() {
  _has_bits_[0] &= ~0x00000001u;
}
void Token::clear_word() {
  word_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_word();
}
const ::std::string& Token::word() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.word)
  return word_.GetNoArena();
}
void Token::set_word(const ::std::string& value) {
  set_has_word();
  word_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Token.word)
}
#if LANG_CXX11
void Token::set_word(::std::string&& value) {
  set_has_word();
  word_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Token.word)
}
#endif
void Token::set_word(const char* value) {
  set_has_word();
  word_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Token.word)
}
void Token::set_word(const char* value, size_t size) {
  set_has_word();
  word_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Token.word)
}
::std::string* Token::mutable_word() {
  set_has_word();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Token.word)
  return word_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Token::release_word() {
  // @@protoc_insertion_point(field_release:syntaxnet.Token.word)
  clear_has_word();
  return word_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Token::set_allocated_word(::std::string* word) {
  if (word != NULL) {
    set_has_word();
  } else {
    clear_has_word();
  }
  word_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), word);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Token.word)
}

// required int32 start = 2;
bool Token::has_start() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Token::set_has_start() {
  _has_bits_[0] |= 0x00000010u;
}
void Token::clear_has_start() {
  _has_bits_[0] &= ~0x00000010u;
}
void Token::clear_start() {
  start_ = 0;
  clear_has_start();
}
::google::protobuf::int32 Token::start() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.start)
  return start_;
}
void Token::set_start(::google::protobuf::int32 value) {
  set_has_start();
  start_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.Token.start)
}

// required int32 end = 3;
bool Token::has_end() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Token::set_has_end() {
  _has_bits_[0] |= 0x00000020u;
}
void Token::clear_has_end() {
  _has_bits_[0] &= ~0x00000020u;
}
void Token::clear_end() {
  end_ = 0;
  clear_has_end();
}
::google::protobuf::int32 Token::end() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.end)
  return end_;
}
void Token::set_end(::google::protobuf::int32 value) {
  set_has_end();
  end_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.Token.end)
}

// optional int32 head = 4 [default = -1];
bool Token::has_head() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void Token::set_has_head() {
  _has_bits_[0] |= 0x00000040u;
}
void Token::clear_has_head() {
  _has_bits_[0] &= ~0x00000040u;
}
void Token::clear_head() {
  head_ = -1;
  clear_has_head();
}
::google::protobuf::int32 Token::head() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.head)
  return head_;
}
void Token::set_head(::google::protobuf::int32 value) {
  set_has_head();
  head_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.Token.head)
}

// optional string tag = 5;
bool Token::has_tag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Token::set_has_tag() {
  _has_bits_[0] |= 0x00000002u;
}
void Token::clear_has_tag() {
  _has_bits_[0] &= ~0x00000002u;
}
void Token::clear_tag() {
  tag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_tag();
}
const ::std::string& Token::tag() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.tag)
  return tag_.GetNoArena();
}
void Token::set_tag(const ::std::string& value) {
  set_has_tag();
  tag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Token.tag)
}
#if LANG_CXX11
void Token::set_tag(::std::string&& value) {
  set_has_tag();
  tag_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Token.tag)
}
#endif
void Token::set_tag(const char* value) {
  set_has_tag();
  tag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Token.tag)
}
void Token::set_tag(const char* value, size_t size) {
  set_has_tag();
  tag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Token.tag)
}
::std::string* Token::mutable_tag() {
  set_has_tag();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Token.tag)
  return tag_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Token::release_tag() {
  // @@protoc_insertion_point(field_release:syntaxnet.Token.tag)
  clear_has_tag();
  return tag_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Token::set_allocated_tag(::std::string* tag) {
  if (tag != NULL) {
    set_has_tag();
  } else {
    clear_has_tag();
  }
  tag_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tag);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Token.tag)
}

// optional string category = 6;
bool Token::has_category() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Token::set_has_category() {
  _has_bits_[0] |= 0x00000004u;
}
void Token::clear_has_category() {
  _has_bits_[0] &= ~0x00000004u;
}
void Token::clear_category() {
  category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_category();
}
const ::std::string& Token::category() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.category)
  return category_.GetNoArena();
}
void Token::set_category(const ::std::string& value) {
  set_has_category();
  category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Token.category)
}
#if LANG_CXX11
void Token::set_category(::std::string&& value) {
  set_has_category();
  category_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Token.category)
}
#endif
void Token::set_category(const char* value) {
  set_has_category();
  category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Token.category)
}
void Token::set_category(const char* value, size_t size) {
  set_has_category();
  category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Token.category)
}
::std::string* Token::mutable_category() {
  set_has_category();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Token.category)
  return category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Token::release_category() {
  // @@protoc_insertion_point(field_release:syntaxnet.Token.category)
  clear_has_category();
  return category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Token::set_allocated_category(::std::string* category) {
  if (category != NULL) {
    set_has_category();
  } else {
    clear_has_category();
  }
  category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), category);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Token.category)
}

// optional string label = 7;
bool Token::has_label() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Token::set_has_label() {
  _has_bits_[0] |= 0x00000008u;
}
void Token::clear_has_label() {
  _has_bits_[0] &= ~0x00000008u;
}
void Token::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_label();
}
const ::std::string& Token::label() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.label)
  return label_.GetNoArena();
}
void Token::set_label(const ::std::string& value) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.Token.label)
}
#if LANG_CXX11
void Token::set_label(::std::string&& value) {
  set_has_label();
  label_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.Token.label)
}
#endif
void Token::set_label(const char* value) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.Token.label)
}
void Token::set_label(const char* value, size_t size) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.Token.label)
}
::std::string* Token::mutable_label() {
  set_has_label();
  // @@protoc_insertion_point(field_mutable:syntaxnet.Token.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Token::release_label() {
  // @@protoc_insertion_point(field_release:syntaxnet.Token.label)
  clear_has_label();
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Token::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    set_has_label();
  } else {
    clear_has_label();
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.Token.label)
}

// optional .syntaxnet.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
bool Token::has_break_level() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void Token::set_has_break_level() {
  _has_bits_[0] |= 0x00000080u;
}
void Token::clear_has_break_level() {
  _has_bits_[0] &= ~0x00000080u;
}
void Token::clear_break_level() {
  break_level_ = 1;
  clear_has_break_level();
}
::syntaxnet::Token_BreakLevel Token::break_level() const {
  // @@protoc_insertion_point(field_get:syntaxnet.Token.break_level)
  return static_cast< ::syntaxnet::Token_BreakLevel >(break_level_);
}
void Token::set_break_level(::syntaxnet::Token_BreakLevel value) {
  assert(::syntaxnet::Token_BreakLevel_IsValid(value));
  set_has_break_level();
  break_level_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.Token.break_level)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenMorphology_Attribute::kNameFieldNumber;
const int TokenMorphology_Attribute::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TokenMorphology_Attribute::TokenMorphology_Attribute()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.TokenMorphology.Attribute)
}
TokenMorphology_Attribute::TokenMorphology_Attribute(const TokenMorphology_Attribute& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_value()) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:syntaxnet.TokenMorphology.Attribute)
}

void TokenMorphology_Attribute::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

TokenMorphology_Attribute::~TokenMorphology_Attribute() {
  // @@protoc_insertion_point(destructor:syntaxnet.TokenMorphology.Attribute)
  SharedDtor();
}

void TokenMorphology_Attribute::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TokenMorphology_Attribute::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TokenMorphology_Attribute::descriptor() {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[2].descriptor;
}

const TokenMorphology_Attribute& TokenMorphology_Attribute::default_instance() {
  protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  return *internal_default_instance();
}

TokenMorphology_Attribute* TokenMorphology_Attribute::New(::google::protobuf::Arena* arena) const {
  TokenMorphology_Attribute* n = new TokenMorphology_Attribute;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TokenMorphology_Attribute::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.TokenMorphology.Attribute)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_name()) {
      GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*name_.UnsafeRawStringPointer())->clear();
    }
    if (has_value()) {
      GOOGLE_DCHECK(!value_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*value_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TokenMorphology_Attribute::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.TokenMorphology.Attribute)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.TokenMorphology.Attribute.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.TokenMorphology.Attribute.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.TokenMorphology.Attribute)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.TokenMorphology.Attribute)
  return false;
#undef DO_
}

void TokenMorphology_Attribute::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.TokenMorphology.Attribute)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.TokenMorphology.Attribute.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.TokenMorphology.Attribute.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.TokenMorphology.Attribute)
}

::google::protobuf::uint8* TokenMorphology_Attribute::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.TokenMorphology.Attribute)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.TokenMorphology.Attribute.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.TokenMorphology.Attribute.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.TokenMorphology.Attribute)
  return target;
}

size_t TokenMorphology_Attribute::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:syntaxnet.TokenMorphology.Attribute)
  size_t total_size = 0;

  if (has_name()) {
    // required string name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  if (has_value()) {
    // required string value = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  return total_size;
}
size_t TokenMorphology_Attribute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.TokenMorphology.Attribute)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

    // required string value = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TokenMorphology_Attribute::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.TokenMorphology.Attribute)
  GOOGLE_DCHECK_NE(&from, this);
  const TokenMorphology_Attribute* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TokenMorphology_Attribute>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.TokenMorphology.Attribute)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.TokenMorphology.Attribute)
    MergeFrom(*source);
  }
}

void TokenMorphology_Attribute::MergeFrom(const TokenMorphology_Attribute& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.TokenMorphology.Attribute)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (from.has_value()) {
      set_has_value();
      value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
    }
  }
}

void TokenMorphology_Attribute::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.TokenMorphology.Attribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TokenMorphology_Attribute::CopyFrom(const TokenMorphology_Attribute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.TokenMorphology.Attribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenMorphology_Attribute::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void TokenMorphology_Attribute::Swap(TokenMorphology_Attribute* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TokenMorphology_Attribute::InternalSwap(TokenMorphology_Attribute* other) {
  name_.Swap(&other->name_);
  value_.Swap(&other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TokenMorphology_Attribute::GetMetadata() const {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenMorphology_Attribute

// required string name = 1;
bool TokenMorphology_Attribute::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TokenMorphology_Attribute::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void TokenMorphology_Attribute::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void TokenMorphology_Attribute::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
const ::std::string& TokenMorphology_Attribute::name() const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenMorphology.Attribute.name)
  return name_.GetNoArena();
}
void TokenMorphology_Attribute::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.TokenMorphology.Attribute.name)
}
#if LANG_CXX11
void TokenMorphology_Attribute::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.TokenMorphology.Attribute.name)
}
#endif
void TokenMorphology_Attribute::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.TokenMorphology.Attribute.name)
}
void TokenMorphology_Attribute::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.TokenMorphology.Attribute.name)
}
::std::string* TokenMorphology_Attribute::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:syntaxnet.TokenMorphology.Attribute.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TokenMorphology_Attribute::release_name() {
  // @@protoc_insertion_point(field_release:syntaxnet.TokenMorphology.Attribute.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TokenMorphology_Attribute::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.TokenMorphology.Attribute.name)
}

// required string value = 2;
bool TokenMorphology_Attribute::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TokenMorphology_Attribute::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
void TokenMorphology_Attribute::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
void TokenMorphology_Attribute::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
const ::std::string& TokenMorphology_Attribute::value() const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenMorphology.Attribute.value)
  return value_.GetNoArena();
}
void TokenMorphology_Attribute::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.TokenMorphology.Attribute.value)
}
#if LANG_CXX11
void TokenMorphology_Attribute::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.TokenMorphology.Attribute.value)
}
#endif
void TokenMorphology_Attribute::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.TokenMorphology.Attribute.value)
}
void TokenMorphology_Attribute::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.TokenMorphology.Attribute.value)
}
::std::string* TokenMorphology_Attribute::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:syntaxnet.TokenMorphology.Attribute.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TokenMorphology_Attribute::release_value() {
  // @@protoc_insertion_point(field_release:syntaxnet.TokenMorphology.Attribute.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TokenMorphology_Attribute::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.TokenMorphology.Attribute.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenMorphology::kAttributeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TokenMorphology::TokenMorphology()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.TokenMorphology)
}
TokenMorphology::TokenMorphology(const TokenMorphology& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      attribute_(from.attribute_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.TokenMorphology)
}

void TokenMorphology::SharedCtor() {
  _cached_size_ = 0;
}

TokenMorphology::~TokenMorphology() {
  // @@protoc_insertion_point(destructor:syntaxnet.TokenMorphology)
  SharedDtor();
}

void TokenMorphology::SharedDtor() {
}

void TokenMorphology::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TokenMorphology::descriptor() {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[3].descriptor;
}

const TokenMorphology& TokenMorphology::default_instance() {
  protobuf_syntaxnet_2fsentence_2eproto::InitDefaults();
  return *internal_default_instance();
}

TokenMorphology* TokenMorphology::New(::google::protobuf::Arena* arena) const {
  TokenMorphology* n = new TokenMorphology;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TokenMorphology::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.TokenMorphology)
  attribute_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TokenMorphology::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.TokenMorphology)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .syntaxnet.TokenMorphology.Attribute attribute = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_attribute()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.TokenMorphology)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.TokenMorphology)
  return false;
#undef DO_
}

void TokenMorphology::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.TokenMorphology)
  // repeated .syntaxnet.TokenMorphology.Attribute attribute = 3;
  for (unsigned int i = 0, n = this->attribute_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->attribute(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.TokenMorphology)
}

::google::protobuf::uint8* TokenMorphology::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.TokenMorphology)
  // repeated .syntaxnet.TokenMorphology.Attribute attribute = 3;
  for (unsigned int i = 0, n = this->attribute_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->attribute(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.TokenMorphology)
  return target;
}

size_t TokenMorphology::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.TokenMorphology)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .syntaxnet.TokenMorphology.Attribute attribute = 3;
  {
    unsigned int count = this->attribute_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->attribute(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TokenMorphology::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.TokenMorphology)
  GOOGLE_DCHECK_NE(&from, this);
  const TokenMorphology* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TokenMorphology>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.TokenMorphology)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.TokenMorphology)
    MergeFrom(*source);
  }
}

void TokenMorphology::MergeFrom(const TokenMorphology& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.TokenMorphology)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  attribute_.MergeFrom(from.attribute_);
}

void TokenMorphology::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.TokenMorphology)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TokenMorphology::CopyFrom(const TokenMorphology& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.TokenMorphology)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenMorphology::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->attribute())) return false;
  return true;
}

void TokenMorphology::Swap(TokenMorphology* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TokenMorphology::InternalSwap(TokenMorphology* other) {
  attribute_.UnsafeArenaSwap(&other->attribute_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TokenMorphology::GetMetadata() const {
  protobuf_syntaxnet_2fsentence_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsentence_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenMorphology

// repeated .syntaxnet.TokenMorphology.Attribute attribute = 3;
int TokenMorphology::attribute_size() const {
  return attribute_.size();
}
void TokenMorphology::clear_attribute() {
  attribute_.Clear();
}
const ::syntaxnet::TokenMorphology_Attribute& TokenMorphology::attribute(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.TokenMorphology.attribute)
  return attribute_.Get(index);
}
::syntaxnet::TokenMorphology_Attribute* TokenMorphology::mutable_attribute(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.TokenMorphology.attribute)
  return attribute_.Mutable(index);
}
::syntaxnet::TokenMorphology_Attribute* TokenMorphology::add_attribute() {
  // @@protoc_insertion_point(field_add:syntaxnet.TokenMorphology.attribute)
  return attribute_.Add();
}
::google::protobuf::RepeatedPtrField< ::syntaxnet::TokenMorphology_Attribute >*
TokenMorphology::mutable_attribute() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.TokenMorphology.attribute)
  return &attribute_;
}
const ::google::protobuf::RepeatedPtrField< ::syntaxnet::TokenMorphology_Attribute >&
TokenMorphology::attribute() const {
  // @@protoc_insertion_point(field_list:syntaxnet.TokenMorphology.attribute)
  return attribute_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenMorphology::kMorphologyFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::syntaxnet::Token,
    ::google::protobuf::internal::MessageTypeTraits< ::syntaxnet::TokenMorphology >, 11, false >
  TokenMorphology::morphology(kMorphologyFieldNumber, *::syntaxnet::TokenMorphology::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)
