// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/sparse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "syntaxnet/sparse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace syntaxnet {
class SparseFeaturesDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SparseFeatures> {
} _SparseFeatures_default_instance_;

namespace protobuf_syntaxnet_2fsparse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SparseFeatures, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SparseFeatures, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SparseFeatures, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SparseFeatures, weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SparseFeatures, description_),
  ~0u,
  ~0u,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(SparseFeatures)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SparseFeatures_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "syntaxnet/sparse.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _SparseFeatures_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SparseFeatures_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\026syntaxnet/sparse.proto\022\tsyntaxnet\"A\n\016S"
      "parseFeatures\022\n\n\002id\030\001 \003(\004\022\016\n\006weight\030\002 \003("
      "\002\022\023\n\013description\030\003 \003(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 102);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "syntaxnet/sparse.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_syntaxnet_2fsparse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SparseFeatures::kIdFieldNumber;
const int SparseFeatures::kWeightFieldNumber;
const int SparseFeatures::kDescriptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SparseFeatures::SparseFeatures()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_syntaxnet_2fsparse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.SparseFeatures)
}
SparseFeatures::SparseFeatures(const SparseFeatures& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      id_(from.id_),
      weight_(from.weight_),
      description_(from.description_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syntaxnet.SparseFeatures)
}

void SparseFeatures::SharedCtor() {
  _cached_size_ = 0;
}

SparseFeatures::~SparseFeatures() {
  // @@protoc_insertion_point(destructor:syntaxnet.SparseFeatures)
  SharedDtor();
}

void SparseFeatures::SharedDtor() {
}

void SparseFeatures::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SparseFeatures::descriptor() {
  protobuf_syntaxnet_2fsparse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsparse_2eproto::file_level_metadata[0].descriptor;
}

const SparseFeatures& SparseFeatures::default_instance() {
  protobuf_syntaxnet_2fsparse_2eproto::InitDefaults();
  return *internal_default_instance();
}

SparseFeatures* SparseFeatures::New(::google::protobuf::Arena* arena) const {
  SparseFeatures* n = new SparseFeatures;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SparseFeatures::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.SparseFeatures)
  id_.Clear();
  weight_.Clear();
  description_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SparseFeatures::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.SparseFeatures)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 8u, input, this->mutable_id())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_id())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 21u, input, this->mutable_weight())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(18u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_weight())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string description = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description(this->description_size() - 1).data(),
            this->description(this->description_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.SparseFeatures.description");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.SparseFeatures)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.SparseFeatures)
  return false;
#undef DO_
}

void SparseFeatures::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.SparseFeatures)
  // repeated uint64 id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      1, this->id(i), output);
  }

  // repeated float weight = 2;
  for (int i = 0, n = this->weight_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      2, this->weight(i), output);
  }

  // repeated string description = 3;
  for (int i = 0, n = this->description_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description(i).data(), this->description(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.SparseFeatures.description");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->description(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.SparseFeatures)
}

::google::protobuf::uint8* SparseFeatures::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.SparseFeatures)
  // repeated uint64 id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(1, this->id(i), target);
  }

  // repeated float weight = 2;
  for (int i = 0, n = this->weight_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(2, this->weight(i), target);
  }

  // repeated string description = 3;
  for (int i = 0, n = this->description_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description(i).data(), this->description(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.SparseFeatures.description");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->description(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.SparseFeatures)
  return target;
}

size_t SparseFeatures::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.SparseFeatures)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated uint64 id = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->id_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->id_size());
    total_size += data_size;
  }

  // repeated float weight = 2;
  {
    unsigned int count = this->weight_size();
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->weight_size());
    total_size += data_size;
  }

  // repeated string description = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->description_size());
  for (int i = 0, n = this->description_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->description(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SparseFeatures::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.SparseFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  const SparseFeatures* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SparseFeatures>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.SparseFeatures)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.SparseFeatures)
    MergeFrom(*source);
  }
}

void SparseFeatures::MergeFrom(const SparseFeatures& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.SparseFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.MergeFrom(from.id_);
  weight_.MergeFrom(from.weight_);
  description_.MergeFrom(from.description_);
}

void SparseFeatures::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.SparseFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SparseFeatures::CopyFrom(const SparseFeatures& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.SparseFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SparseFeatures::IsInitialized() const {
  return true;
}

void SparseFeatures::Swap(SparseFeatures* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SparseFeatures::InternalSwap(SparseFeatures* other) {
  id_.UnsafeArenaSwap(&other->id_);
  weight_.UnsafeArenaSwap(&other->weight_);
  description_.UnsafeArenaSwap(&other->description_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SparseFeatures::GetMetadata() const {
  protobuf_syntaxnet_2fsparse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_syntaxnet_2fsparse_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SparseFeatures

// repeated uint64 id = 1;
int SparseFeatures::id_size() const {
  return id_.size();
}
void SparseFeatures::clear_id() {
  id_.Clear();
}
::google::protobuf::uint64 SparseFeatures::id(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.id)
  return id_.Get(index);
}
void SparseFeatures::set_id(int index, ::google::protobuf::uint64 value) {
  id_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.id)
}
void SparseFeatures::add_id(::google::protobuf::uint64 value) {
  id_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.id)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SparseFeatures::id() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.id)
  return id_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SparseFeatures::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.id)
  return &id_;
}

// repeated float weight = 2;
int SparseFeatures::weight_size() const {
  return weight_.size();
}
void SparseFeatures::clear_weight() {
  weight_.Clear();
}
float SparseFeatures::weight(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.weight)
  return weight_.Get(index);
}
void SparseFeatures::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.weight)
}
void SparseFeatures::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.weight)
}
const ::google::protobuf::RepeatedField< float >&
SparseFeatures::weight() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.weight)
  return weight_;
}
::google::protobuf::RepeatedField< float >*
SparseFeatures::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.weight)
  return &weight_;
}

// repeated string description = 3;
int SparseFeatures::description_size() const {
  return description_.size();
}
void SparseFeatures::clear_description() {
  description_.Clear();
}
const ::std::string& SparseFeatures::description(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.description)
  return description_.Get(index);
}
::std::string* SparseFeatures::mutable_description(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.SparseFeatures.description)
  return description_.Mutable(index);
}
void SparseFeatures::set_description(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.description)
  description_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void SparseFeatures::set_description(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.description)
  description_.Mutable(index)->assign(std::move(value));
}
#endif
void SparseFeatures::set_description(int index, const char* value) {
  description_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.SparseFeatures.description)
}
void SparseFeatures::set_description(int index, const char* value, size_t size) {
  description_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.SparseFeatures.description)
}
::std::string* SparseFeatures::add_description() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.SparseFeatures.description)
  return description_.Add();
}
void SparseFeatures::add_description(const ::std::string& value) {
  description_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.description)
}
#if LANG_CXX11
void SparseFeatures::add_description(::std::string&& value) {
  description_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.description)
}
#endif
void SparseFeatures::add_description(const char* value) {
  description_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.SparseFeatures.description)
}
void SparseFeatures::add_description(const char* value, size_t size) {
  description_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.SparseFeatures.description)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
SparseFeatures::description() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.description)
  return description_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
SparseFeatures::mutable_description() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.description)
  return &description_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)
