# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syntaxnet/sparse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='syntaxnet/sparse.proto',
  package='syntaxnet',
  syntax='proto2',
  serialized_pb=_b('\n\x16syntaxnet/sparse.proto\x12\tsyntaxnet\"A\n\x0eSparseFeatures\x12\n\n\x02id\x18\x01 \x03(\x04\x12\x0e\n\x06weight\x18\x02 \x03(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPARSEFEATURES = _descriptor.Descriptor(
  name='SparseFeatures',
  full_name='syntaxnet.SparseFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='syntaxnet.SparseFeatures.id', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='syntaxnet.SparseFeatures.weight', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='syntaxnet.SparseFeatures.description', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['SparseFeatures'] = _SPARSEFEATURES

SparseFeatures = _reflection.GeneratedProtocolMessageType('SparseFeatures', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEFEATURES,
  __module__ = 'syntaxnet.sparse_pb2'
  # @@protoc_insertion_point(class_scope:syntaxnet.SparseFeatures)
  ))
_sym_db.RegisterMessage(SparseFeatures)


# @@protoc_insertion_point(module_scope)
