// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syntaxnet/sparse.proto

#ifndef PROTOBUF_syntaxnet_2fsparse_2eproto__INCLUDED
#define PROTOBUF_syntaxnet_2fsparse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace syntaxnet {
class SparseFeatures;
class SparseFeaturesDefaultTypeInternal;
extern SparseFeaturesDefaultTypeInternal _SparseFeatures_default_instance_;
}  // namespace syntaxnet

namespace syntaxnet {

namespace protobuf_syntaxnet_2fsparse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_syntaxnet_2fsparse_2eproto

// ===================================================================

class SparseFeatures : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:syntaxnet.SparseFeatures) */ {
 public:
  SparseFeatures();
  virtual ~SparseFeatures();

  SparseFeatures(const SparseFeatures& from);

  inline SparseFeatures& operator=(const SparseFeatures& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SparseFeatures& default_instance();

  static inline const SparseFeatures* internal_default_instance() {
    return reinterpret_cast<const SparseFeatures*>(
               &_SparseFeatures_default_instance_);
  }

  void Swap(SparseFeatures* other);

  // implements Message ----------------------------------------------

  inline SparseFeatures* New() const PROTOBUF_FINAL { return New(NULL); }

  SparseFeatures* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SparseFeatures& from);
  void MergeFrom(const SparseFeatures& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SparseFeatures* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 id = 1;
  int id_size() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id(int index) const;
  void set_id(int index, ::google::protobuf::uint64 value);
  void add_id(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_id();

  // repeated float weight = 2;
  int weight_size() const;
  void clear_weight();
  static const int kWeightFieldNumber = 2;
  float weight(int index) const;
  void set_weight(int index, float value);
  void add_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_weight();

  // repeated string description = 3;
  int description_size() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 3;
  const ::std::string& description(int index) const;
  ::std::string* mutable_description(int index);
  void set_description(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_description(int index, ::std::string&& value);
  #endif
  void set_description(int index, const char* value);
  void set_description(int index, const char* value, size_t size);
  ::std::string* add_description();
  void add_description(const ::std::string& value);
  #if LANG_CXX11
  void add_description(::std::string&& value);
  #endif
  void add_description(const char* value);
  void add_description(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& description() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_description();

  // @@protoc_insertion_point(class_scope:syntaxnet.SparseFeatures)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > id_;
  ::google::protobuf::RepeatedField< float > weight_;
  ::google::protobuf::RepeatedPtrField< ::std::string> description_;
  friend struct  protobuf_syntaxnet_2fsparse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SparseFeatures

// repeated uint64 id = 1;
inline int SparseFeatures::id_size() const {
  return id_.size();
}
inline void SparseFeatures::clear_id() {
  id_.Clear();
}
inline ::google::protobuf::uint64 SparseFeatures::id(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.id)
  return id_.Get(index);
}
inline void SparseFeatures::set_id(int index, ::google::protobuf::uint64 value) {
  id_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.id)
}
inline void SparseFeatures::add_id(::google::protobuf::uint64 value) {
  id_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SparseFeatures::id() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.id)
  return id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SparseFeatures::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.id)
  return &id_;
}

// repeated float weight = 2;
inline int SparseFeatures::weight_size() const {
  return weight_.size();
}
inline void SparseFeatures::clear_weight() {
  weight_.Clear();
}
inline float SparseFeatures::weight(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.weight)
  return weight_.Get(index);
}
inline void SparseFeatures::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.weight)
}
inline void SparseFeatures::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.weight)
}
inline const ::google::protobuf::RepeatedField< float >&
SparseFeatures::weight() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.weight)
  return weight_;
}
inline ::google::protobuf::RepeatedField< float >*
SparseFeatures::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.weight)
  return &weight_;
}

// repeated string description = 3;
inline int SparseFeatures::description_size() const {
  return description_.size();
}
inline void SparseFeatures::clear_description() {
  description_.Clear();
}
inline const ::std::string& SparseFeatures::description(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.SparseFeatures.description)
  return description_.Get(index);
}
inline ::std::string* SparseFeatures::mutable_description(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.SparseFeatures.description)
  return description_.Mutable(index);
}
inline void SparseFeatures::set_description(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.description)
  description_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void SparseFeatures::set_description(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.SparseFeatures.description)
  description_.Mutable(index)->assign(std::move(value));
}
#endif
inline void SparseFeatures::set_description(int index, const char* value) {
  description_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.SparseFeatures.description)
}
inline void SparseFeatures::set_description(int index, const char* value, size_t size) {
  description_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.SparseFeatures.description)
}
inline ::std::string* SparseFeatures::add_description() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.SparseFeatures.description)
  return description_.Add();
}
inline void SparseFeatures::add_description(const ::std::string& value) {
  description_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.description)
}
#if LANG_CXX11
inline void SparseFeatures::add_description(::std::string&& value) {
  description_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.SparseFeatures.description)
}
#endif
inline void SparseFeatures::add_description(const char* value) {
  description_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.SparseFeatures.description)
}
inline void SparseFeatures::add_description(const char* value, size_t size) {
  description_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.SparseFeatures.description)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SparseFeatures::description() const {
  // @@protoc_insertion_point(field_list:syntaxnet.SparseFeatures.description)
  return description_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SparseFeatures::mutable_description() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.SparseFeatures.description)
  return &description_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_syntaxnet_2fsparse_2eproto__INCLUDED
