// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dragnn/protos/data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dragnn/protos/data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace syntaxnet {
namespace dragnn {
class FixedFeaturesDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FixedFeatures> {
} _FixedFeatures_default_instance_;
class LinkFeaturesDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<LinkFeatures> {
} _LinkFeatures_default_instance_;

namespace protobuf_dragnn_2fprotos_2fdata_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, value_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FixedFeatures, feature_name_),
  ~0u,
  ~0u,
  ~0u,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, batch_idx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, beam_idx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, step_idx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, feature_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkFeatures, feature_name_),
  1,
  2,
  3,
  4,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(FixedFeatures)},
  { 12, 21, sizeof(LinkFeatures)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_FixedFeatures_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_LinkFeatures_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "dragnn/protos/data.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _FixedFeatures_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _LinkFeatures_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _FixedFeatures_default_instance_.DefaultConstruct();
  _LinkFeatures_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030dragnn/protos/data.proto\022\020syntaxnet.dr"
      "agnn\"U\n\rFixedFeatures\022\n\n\002id\030\001 \003(\004\022\016\n\006wei"
      "ght\030\002 \003(\002\022\022\n\nvalue_name\030\003 \003(\t\022\024\n\014feature"
      "_name\030\004 \001(\t\"r\n\014LinkFeatures\022\021\n\tbatch_idx"
      "\030\001 \001(\003\022\020\n\010beam_idx\030\002 \001(\003\022\020\n\010step_idx\030\003 \001"
      "(\003\022\025\n\rfeature_value\030\004 \001(\003\022\024\n\014feature_nam"
      "e\030\005 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 247);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dragnn/protos/data.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_dragnn_2fprotos_2fdata_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FixedFeatures::kIdFieldNumber;
const int FixedFeatures::kWeightFieldNumber;
const int FixedFeatures::kValueNameFieldNumber;
const int FixedFeatures::kFeatureNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FixedFeatures::FixedFeatures()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_dragnn_2fprotos_2fdata_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.dragnn.FixedFeatures)
}
FixedFeatures::FixedFeatures(const FixedFeatures& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      id_(from.id_),
      weight_(from.weight_),
      value_name_(from.value_name_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  feature_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_feature_name()) {
    feature_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.feature_name_);
  }
  // @@protoc_insertion_point(copy_constructor:syntaxnet.dragnn.FixedFeatures)
}

void FixedFeatures::SharedCtor() {
  _cached_size_ = 0;
  feature_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FixedFeatures::~FixedFeatures() {
  // @@protoc_insertion_point(destructor:syntaxnet.dragnn.FixedFeatures)
  SharedDtor();
}

void FixedFeatures::SharedDtor() {
  feature_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FixedFeatures::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FixedFeatures::descriptor() {
  protobuf_dragnn_2fprotos_2fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dragnn_2fprotos_2fdata_2eproto::file_level_metadata[0].descriptor;
}

const FixedFeatures& FixedFeatures::default_instance() {
  protobuf_dragnn_2fprotos_2fdata_2eproto::InitDefaults();
  return *internal_default_instance();
}

FixedFeatures* FixedFeatures::New(::google::protobuf::Arena* arena) const {
  FixedFeatures* n = new FixedFeatures;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FixedFeatures::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.dragnn.FixedFeatures)
  id_.Clear();
  weight_.Clear();
  value_name_.Clear();
  if (has_feature_name()) {
    GOOGLE_DCHECK(!feature_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*feature_name_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool FixedFeatures::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.dragnn.FixedFeatures)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 8u, input, this->mutable_id())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_id())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 21u, input, this->mutable_weight())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(18u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_weight())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string value_name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value_name(this->value_name_size() - 1).data(),
            this->value_name(this->value_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.dragnn.FixedFeatures.value_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string feature_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_feature_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->feature_name().data(), this->feature_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.dragnn.FixedFeatures.feature_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.dragnn.FixedFeatures)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.dragnn.FixedFeatures)
  return false;
#undef DO_
}

void FixedFeatures::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.dragnn.FixedFeatures)
  // repeated uint64 id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      1, this->id(i), output);
  }

  // repeated float weight = 2;
  for (int i = 0, n = this->weight_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      2, this->weight(i), output);
  }

  // repeated string value_name = 3;
  for (int i = 0, n = this->value_name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value_name(i).data(), this->value_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.FixedFeatures.value_name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->value_name(i), output);
  }

  // optional string feature_name = 4;
  if (has_feature_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->feature_name().data(), this->feature_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.FixedFeatures.feature_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->feature_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.dragnn.FixedFeatures)
}

::google::protobuf::uint8* FixedFeatures::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.dragnn.FixedFeatures)
  // repeated uint64 id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(1, this->id(i), target);
  }

  // repeated float weight = 2;
  for (int i = 0, n = this->weight_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(2, this->weight(i), target);
  }

  // repeated string value_name = 3;
  for (int i = 0, n = this->value_name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value_name(i).data(), this->value_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.FixedFeatures.value_name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->value_name(i), target);
  }

  // optional string feature_name = 4;
  if (has_feature_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->feature_name().data(), this->feature_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.FixedFeatures.feature_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->feature_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.dragnn.FixedFeatures)
  return target;
}

size_t FixedFeatures::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.dragnn.FixedFeatures)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated uint64 id = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->id_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->id_size());
    total_size += data_size;
  }

  // repeated float weight = 2;
  {
    unsigned int count = this->weight_size();
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->weight_size());
    total_size += data_size;
  }

  // repeated string value_name = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->value_name_size());
  for (int i = 0, n = this->value_name_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value_name(i));
  }

  // optional string feature_name = 4;
  if (has_feature_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->feature_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FixedFeatures::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.dragnn.FixedFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  const FixedFeatures* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FixedFeatures>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.dragnn.FixedFeatures)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.dragnn.FixedFeatures)
    MergeFrom(*source);
  }
}

void FixedFeatures::MergeFrom(const FixedFeatures& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.dragnn.FixedFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.MergeFrom(from.id_);
  weight_.MergeFrom(from.weight_);
  value_name_.MergeFrom(from.value_name_);
  if (from.has_feature_name()) {
    set_has_feature_name();
    feature_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.feature_name_);
  }
}

void FixedFeatures::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.dragnn.FixedFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FixedFeatures::CopyFrom(const FixedFeatures& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.dragnn.FixedFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FixedFeatures::IsInitialized() const {
  return true;
}

void FixedFeatures::Swap(FixedFeatures* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FixedFeatures::InternalSwap(FixedFeatures* other) {
  id_.UnsafeArenaSwap(&other->id_);
  weight_.UnsafeArenaSwap(&other->weight_);
  value_name_.UnsafeArenaSwap(&other->value_name_);
  feature_name_.Swap(&other->feature_name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FixedFeatures::GetMetadata() const {
  protobuf_dragnn_2fprotos_2fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dragnn_2fprotos_2fdata_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FixedFeatures

// repeated uint64 id = 1;
int FixedFeatures::id_size() const {
  return id_.size();
}
void FixedFeatures::clear_id() {
  id_.Clear();
}
::google::protobuf::uint64 FixedFeatures::id(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.FixedFeatures.id)
  return id_.Get(index);
}
void FixedFeatures::set_id(int index, ::google::protobuf::uint64 value) {
  id_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.FixedFeatures.id)
}
void FixedFeatures::add_id(::google::protobuf::uint64 value) {
  id_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.dragnn.FixedFeatures.id)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
FixedFeatures::id() const {
  // @@protoc_insertion_point(field_list:syntaxnet.dragnn.FixedFeatures.id)
  return id_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
FixedFeatures::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.dragnn.FixedFeatures.id)
  return &id_;
}

// repeated float weight = 2;
int FixedFeatures::weight_size() const {
  return weight_.size();
}
void FixedFeatures::clear_weight() {
  weight_.Clear();
}
float FixedFeatures::weight(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.FixedFeatures.weight)
  return weight_.Get(index);
}
void FixedFeatures::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.FixedFeatures.weight)
}
void FixedFeatures::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:syntaxnet.dragnn.FixedFeatures.weight)
}
const ::google::protobuf::RepeatedField< float >&
FixedFeatures::weight() const {
  // @@protoc_insertion_point(field_list:syntaxnet.dragnn.FixedFeatures.weight)
  return weight_;
}
::google::protobuf::RepeatedField< float >*
FixedFeatures::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.dragnn.FixedFeatures.weight)
  return &weight_;
}

// repeated string value_name = 3;
int FixedFeatures::value_name_size() const {
  return value_name_.size();
}
void FixedFeatures::clear_value_name() {
  value_name_.Clear();
}
const ::std::string& FixedFeatures::value_name(int index) const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.FixedFeatures.value_name)
  return value_name_.Get(index);
}
::std::string* FixedFeatures::mutable_value_name(int index) {
  // @@protoc_insertion_point(field_mutable:syntaxnet.dragnn.FixedFeatures.value_name)
  return value_name_.Mutable(index);
}
void FixedFeatures::set_value_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.FixedFeatures.value_name)
  value_name_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void FixedFeatures::set_value_name(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.FixedFeatures.value_name)
  value_name_.Mutable(index)->assign(std::move(value));
}
#endif
void FixedFeatures::set_value_name(int index, const char* value) {
  value_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:syntaxnet.dragnn.FixedFeatures.value_name)
}
void FixedFeatures::set_value_name(int index, const char* value, size_t size) {
  value_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.dragnn.FixedFeatures.value_name)
}
::std::string* FixedFeatures::add_value_name() {
  // @@protoc_insertion_point(field_add_mutable:syntaxnet.dragnn.FixedFeatures.value_name)
  return value_name_.Add();
}
void FixedFeatures::add_value_name(const ::std::string& value) {
  value_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:syntaxnet.dragnn.FixedFeatures.value_name)
}
#if LANG_CXX11
void FixedFeatures::add_value_name(::std::string&& value) {
  value_name_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:syntaxnet.dragnn.FixedFeatures.value_name)
}
#endif
void FixedFeatures::add_value_name(const char* value) {
  value_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:syntaxnet.dragnn.FixedFeatures.value_name)
}
void FixedFeatures::add_value_name(const char* value, size_t size) {
  value_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:syntaxnet.dragnn.FixedFeatures.value_name)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
FixedFeatures::value_name() const {
  // @@protoc_insertion_point(field_list:syntaxnet.dragnn.FixedFeatures.value_name)
  return value_name_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
FixedFeatures::mutable_value_name() {
  // @@protoc_insertion_point(field_mutable_list:syntaxnet.dragnn.FixedFeatures.value_name)
  return &value_name_;
}

// optional string feature_name = 4;
bool FixedFeatures::has_feature_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void FixedFeatures::set_has_feature_name() {
  _has_bits_[0] |= 0x00000001u;
}
void FixedFeatures::clear_has_feature_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void FixedFeatures::clear_feature_name() {
  feature_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_feature_name();
}
const ::std::string& FixedFeatures::feature_name() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.FixedFeatures.feature_name)
  return feature_name_.GetNoArena();
}
void FixedFeatures::set_feature_name(const ::std::string& value) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.FixedFeatures.feature_name)
}
#if LANG_CXX11
void FixedFeatures::set_feature_name(::std::string&& value) {
  set_has_feature_name();
  feature_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.dragnn.FixedFeatures.feature_name)
}
#endif
void FixedFeatures::set_feature_name(const char* value) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.dragnn.FixedFeatures.feature_name)
}
void FixedFeatures::set_feature_name(const char* value, size_t size) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.dragnn.FixedFeatures.feature_name)
}
::std::string* FixedFeatures::mutable_feature_name() {
  set_has_feature_name();
  // @@protoc_insertion_point(field_mutable:syntaxnet.dragnn.FixedFeatures.feature_name)
  return feature_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* FixedFeatures::release_feature_name() {
  // @@protoc_insertion_point(field_release:syntaxnet.dragnn.FixedFeatures.feature_name)
  clear_has_feature_name();
  return feature_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void FixedFeatures::set_allocated_feature_name(::std::string* feature_name) {
  if (feature_name != NULL) {
    set_has_feature_name();
  } else {
    clear_has_feature_name();
  }
  feature_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), feature_name);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.dragnn.FixedFeatures.feature_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LinkFeatures::kBatchIdxFieldNumber;
const int LinkFeatures::kBeamIdxFieldNumber;
const int LinkFeatures::kStepIdxFieldNumber;
const int LinkFeatures::kFeatureValueFieldNumber;
const int LinkFeatures::kFeatureNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LinkFeatures::LinkFeatures()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_dragnn_2fprotos_2fdata_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:syntaxnet.dragnn.LinkFeatures)
}
LinkFeatures::LinkFeatures(const LinkFeatures& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  feature_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_feature_name()) {
    feature_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.feature_name_);
  }
  ::memcpy(&batch_idx_, &from.batch_idx_,
    reinterpret_cast<char*>(&feature_value_) -
    reinterpret_cast<char*>(&batch_idx_) + sizeof(feature_value_));
  // @@protoc_insertion_point(copy_constructor:syntaxnet.dragnn.LinkFeatures)
}

void LinkFeatures::SharedCtor() {
  _cached_size_ = 0;
  feature_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&batch_idx_, 0, reinterpret_cast<char*>(&feature_value_) -
    reinterpret_cast<char*>(&batch_idx_) + sizeof(feature_value_));
}

LinkFeatures::~LinkFeatures() {
  // @@protoc_insertion_point(destructor:syntaxnet.dragnn.LinkFeatures)
  SharedDtor();
}

void LinkFeatures::SharedDtor() {
  feature_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LinkFeatures::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LinkFeatures::descriptor() {
  protobuf_dragnn_2fprotos_2fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dragnn_2fprotos_2fdata_2eproto::file_level_metadata[1].descriptor;
}

const LinkFeatures& LinkFeatures::default_instance() {
  protobuf_dragnn_2fprotos_2fdata_2eproto::InitDefaults();
  return *internal_default_instance();
}

LinkFeatures* LinkFeatures::New(::google::protobuf::Arena* arena) const {
  LinkFeatures* n = new LinkFeatures;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LinkFeatures::Clear() {
// @@protoc_insertion_point(message_clear_start:syntaxnet.dragnn.LinkFeatures)
  if (has_feature_name()) {
    GOOGLE_DCHECK(!feature_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*feature_name_.UnsafeRawStringPointer())->clear();
  }
  if (_has_bits_[0 / 32] & 30u) {
    ::memset(&batch_idx_, 0, reinterpret_cast<char*>(&feature_value_) -
      reinterpret_cast<char*>(&batch_idx_) + sizeof(feature_value_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool LinkFeatures::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:syntaxnet.dragnn.LinkFeatures)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 batch_idx = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_batch_idx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &batch_idx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 beam_idx = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_beam_idx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &beam_idx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 step_idx = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_step_idx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &step_idx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 feature_value = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          set_has_feature_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &feature_value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string feature_name = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_feature_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->feature_name().data(), this->feature_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "syntaxnet.dragnn.LinkFeatures.feature_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:syntaxnet.dragnn.LinkFeatures)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:syntaxnet.dragnn.LinkFeatures)
  return false;
#undef DO_
}

void LinkFeatures::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:syntaxnet.dragnn.LinkFeatures)
  // optional int64 batch_idx = 1;
  if (has_batch_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->batch_idx(), output);
  }

  // optional int64 beam_idx = 2;
  if (has_beam_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->beam_idx(), output);
  }

  // optional int64 step_idx = 3;
  if (has_step_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->step_idx(), output);
  }

  // optional int64 feature_value = 4;
  if (has_feature_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->feature_value(), output);
  }

  // optional string feature_name = 5;
  if (has_feature_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->feature_name().data(), this->feature_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.LinkFeatures.feature_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->feature_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:syntaxnet.dragnn.LinkFeatures)
}

::google::protobuf::uint8* LinkFeatures::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:syntaxnet.dragnn.LinkFeatures)
  // optional int64 batch_idx = 1;
  if (has_batch_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->batch_idx(), target);
  }

  // optional int64 beam_idx = 2;
  if (has_beam_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->beam_idx(), target);
  }

  // optional int64 step_idx = 3;
  if (has_step_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->step_idx(), target);
  }

  // optional int64 feature_value = 4;
  if (has_feature_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->feature_value(), target);
  }

  // optional string feature_name = 5;
  if (has_feature_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->feature_name().data(), this->feature_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "syntaxnet.dragnn.LinkFeatures.feature_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->feature_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syntaxnet.dragnn.LinkFeatures)
  return target;
}

size_t LinkFeatures::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syntaxnet.dragnn.LinkFeatures)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 31u) {
    // optional string feature_name = 5;
    if (has_feature_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->feature_name());
    }

    // optional int64 batch_idx = 1;
    if (has_batch_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->batch_idx());
    }

    // optional int64 beam_idx = 2;
    if (has_beam_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->beam_idx());
    }

    // optional int64 step_idx = 3;
    if (has_step_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->step_idx());
    }

    // optional int64 feature_value = 4;
    if (has_feature_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->feature_value());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LinkFeatures::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syntaxnet.dragnn.LinkFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  const LinkFeatures* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LinkFeatures>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syntaxnet.dragnn.LinkFeatures)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syntaxnet.dragnn.LinkFeatures)
    MergeFrom(*source);
  }
}

void LinkFeatures::MergeFrom(const LinkFeatures& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syntaxnet.dragnn.LinkFeatures)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 31u) {
    if (from.has_feature_name()) {
      set_has_feature_name();
      feature_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.feature_name_);
    }
    if (from.has_batch_idx()) {
      set_batch_idx(from.batch_idx());
    }
    if (from.has_beam_idx()) {
      set_beam_idx(from.beam_idx());
    }
    if (from.has_step_idx()) {
      set_step_idx(from.step_idx());
    }
    if (from.has_feature_value()) {
      set_feature_value(from.feature_value());
    }
  }
}

void LinkFeatures::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syntaxnet.dragnn.LinkFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LinkFeatures::CopyFrom(const LinkFeatures& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syntaxnet.dragnn.LinkFeatures)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LinkFeatures::IsInitialized() const {
  return true;
}

void LinkFeatures::Swap(LinkFeatures* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LinkFeatures::InternalSwap(LinkFeatures* other) {
  feature_name_.Swap(&other->feature_name_);
  std::swap(batch_idx_, other->batch_idx_);
  std::swap(beam_idx_, other->beam_idx_);
  std::swap(step_idx_, other->step_idx_);
  std::swap(feature_value_, other->feature_value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LinkFeatures::GetMetadata() const {
  protobuf_dragnn_2fprotos_2fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dragnn_2fprotos_2fdata_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LinkFeatures

// optional int64 batch_idx = 1;
bool LinkFeatures::has_batch_idx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void LinkFeatures::set_has_batch_idx() {
  _has_bits_[0] |= 0x00000002u;
}
void LinkFeatures::clear_has_batch_idx() {
  _has_bits_[0] &= ~0x00000002u;
}
void LinkFeatures::clear_batch_idx() {
  batch_idx_ = GOOGLE_LONGLONG(0);
  clear_has_batch_idx();
}
::google::protobuf::int64 LinkFeatures::batch_idx() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.LinkFeatures.batch_idx)
  return batch_idx_;
}
void LinkFeatures::set_batch_idx(::google::protobuf::int64 value) {
  set_has_batch_idx();
  batch_idx_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.LinkFeatures.batch_idx)
}

// optional int64 beam_idx = 2;
bool LinkFeatures::has_beam_idx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void LinkFeatures::set_has_beam_idx() {
  _has_bits_[0] |= 0x00000004u;
}
void LinkFeatures::clear_has_beam_idx() {
  _has_bits_[0] &= ~0x00000004u;
}
void LinkFeatures::clear_beam_idx() {
  beam_idx_ = GOOGLE_LONGLONG(0);
  clear_has_beam_idx();
}
::google::protobuf::int64 LinkFeatures::beam_idx() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.LinkFeatures.beam_idx)
  return beam_idx_;
}
void LinkFeatures::set_beam_idx(::google::protobuf::int64 value) {
  set_has_beam_idx();
  beam_idx_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.LinkFeatures.beam_idx)
}

// optional int64 step_idx = 3;
bool LinkFeatures::has_step_idx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void LinkFeatures::set_has_step_idx() {
  _has_bits_[0] |= 0x00000008u;
}
void LinkFeatures::clear_has_step_idx() {
  _has_bits_[0] &= ~0x00000008u;
}
void LinkFeatures::clear_step_idx() {
  step_idx_ = GOOGLE_LONGLONG(0);
  clear_has_step_idx();
}
::google::protobuf::int64 LinkFeatures::step_idx() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.LinkFeatures.step_idx)
  return step_idx_;
}
void LinkFeatures::set_step_idx(::google::protobuf::int64 value) {
  set_has_step_idx();
  step_idx_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.LinkFeatures.step_idx)
}

// optional int64 feature_value = 4;
bool LinkFeatures::has_feature_value() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void LinkFeatures::set_has_feature_value() {
  _has_bits_[0] |= 0x00000010u;
}
void LinkFeatures::clear_has_feature_value() {
  _has_bits_[0] &= ~0x00000010u;
}
void LinkFeatures::clear_feature_value() {
  feature_value_ = GOOGLE_LONGLONG(0);
  clear_has_feature_value();
}
::google::protobuf::int64 LinkFeatures::feature_value() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.LinkFeatures.feature_value)
  return feature_value_;
}
void LinkFeatures::set_feature_value(::google::protobuf::int64 value) {
  set_has_feature_value();
  feature_value_ = value;
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.LinkFeatures.feature_value)
}

// optional string feature_name = 5;
bool LinkFeatures::has_feature_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void LinkFeatures::set_has_feature_name() {
  _has_bits_[0] |= 0x00000001u;
}
void LinkFeatures::clear_has_feature_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void LinkFeatures::clear_feature_name() {
  feature_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_feature_name();
}
const ::std::string& LinkFeatures::feature_name() const {
  // @@protoc_insertion_point(field_get:syntaxnet.dragnn.LinkFeatures.feature_name)
  return feature_name_.GetNoArena();
}
void LinkFeatures::set_feature_name(const ::std::string& value) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:syntaxnet.dragnn.LinkFeatures.feature_name)
}
#if LANG_CXX11
void LinkFeatures::set_feature_name(::std::string&& value) {
  set_has_feature_name();
  feature_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:syntaxnet.dragnn.LinkFeatures.feature_name)
}
#endif
void LinkFeatures::set_feature_name(const char* value) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:syntaxnet.dragnn.LinkFeatures.feature_name)
}
void LinkFeatures::set_feature_name(const char* value, size_t size) {
  set_has_feature_name();
  feature_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:syntaxnet.dragnn.LinkFeatures.feature_name)
}
::std::string* LinkFeatures::mutable_feature_name() {
  set_has_feature_name();
  // @@protoc_insertion_point(field_mutable:syntaxnet.dragnn.LinkFeatures.feature_name)
  return feature_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LinkFeatures::release_feature_name() {
  // @@protoc_insertion_point(field_release:syntaxnet.dragnn.LinkFeatures.feature_name)
  clear_has_feature_name();
  return feature_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LinkFeatures::set_allocated_feature_name(::std::string* feature_name) {
  if (feature_name != NULL) {
    set_has_feature_name();
  } else {
    clear_has_feature_name();
  }
  feature_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), feature_name);
  // @@protoc_insertion_point(field_set_allocated:syntaxnet.dragnn.LinkFeatures.feature_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace dragnn
}  // namespace syntaxnet

// @@protoc_insertion_point(global_scope)
